-- REVIEW ONLY - NO EJECUTAR SIN APROBACION EXPLICITA DEL USUARIO.
-- Proyecto permitido: mixyhfdlzjarvszinytk (cerdova-db).
-- Proyecto prohibido: hmyzuuujyurvyuusvyzp.
--
-- Este script:
-- 1. Agrega permisos por modulo sin crear nuevos valores de perfiles.rol.
-- 2. Agrega asignacion y campos de gestion a requerimientos.
-- 3. Crea reglas configurables de ruteo (inicialmente vacias).
-- 4. Reemplaza TODAS las politicas RLS actuales de requerimientos.
-- 5. No crea usuarios, no inserta responsables y no borra requerimientos.

begin;

create schema if not exists bitacora_private;
revoke all on schema bitacora_private from public, anon;
grant usage on schema bitacora_private to authenticated;

create table if not exists bitacora.perfil_permisos (
  id bigint generated by default as identity primary key,
  perfil_id uuid not null references bitacora.perfiles(id) on delete cascade,
  modulo text not null,
  accion text not null,
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  created_by uuid references bitacora.perfiles(id),
  constraint perfil_permisos_modulo_check check (modulo in ('compras')),
  constraint perfil_permisos_accion_check check (accion in ('request','manage','supervise','invoice')),
  constraint perfil_permisos_unique unique (perfil_id, modulo, accion)
);

alter table bitacora.perfil_permisos enable row level security;
revoke all on table bitacora.perfil_permisos from anon;
revoke all on table bitacora.perfil_permisos from authenticated;
grant select, insert, update on table bitacora.perfil_permisos to authenticated;
grant usage, select on sequence bitacora.perfil_permisos_id_seq to authenticated;

create or replace function bitacora_private.is_active_profile()
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, bitacora
as $$
  select exists (
    select 1 from bitacora.perfiles p
    where p.id = auth.uid() and p.activo = true
  );
$$;

create or replace function bitacora_private.is_admin_or_editor()
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, bitacora
as $$
  select exists (
    select 1 from bitacora.perfiles p
    where p.id = auth.uid() and p.activo = true and p.rol in ('admin','editor')
  );
$$;

create or replace function bitacora_private.is_admin()
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, bitacora
as $$
  select exists (
    select 1 from bitacora.perfiles p
    where p.id = auth.uid() and p.activo = true and p.rol = 'admin'
  );
$$;

create or replace function bitacora_private.has_compras_permission(required_action text)
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, bitacora
as $$
  select bitacora_private.is_admin_or_editor()
    or exists (
      select 1 from bitacora.perfil_permisos pp
      join bitacora.perfiles p on p.id = pp.perfil_id and p.activo = true
      where pp.perfil_id = auth.uid()
        and pp.modulo = 'compras'
        and pp.accion = required_action
        and pp.activo = true
    );
$$;

create or replace function bitacora_private.is_purchase_approver()
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, bitacora
as $$
  select exists (
    select 1 from bitacora.perfiles p
    where p.id = auth.uid()
      and p.activo = true
      and p.rol in ('admin','editor','grupo','encargado')
  );
$$;

revoke all on function bitacora_private.is_active_profile() from public, anon;
revoke all on function bitacora_private.is_admin_or_editor() from public, anon;
revoke all on function bitacora_private.is_admin() from public, anon;
revoke all on function bitacora_private.has_compras_permission(text) from public, anon;
revoke all on function bitacora_private.is_purchase_approver() from public, anon;
grant execute on function bitacora_private.is_active_profile() to authenticated;
grant execute on function bitacora_private.is_admin_or_editor() to authenticated;
grant execute on function bitacora_private.is_admin() to authenticated;
grant execute on function bitacora_private.has_compras_permission(text) to authenticated;
grant execute on function bitacora_private.is_purchase_approver() to authenticated;

drop policy if exists perfil_permisos_select_self_or_admin on bitacora.perfil_permisos;
drop policy if exists perfil_permisos_insert_admin on bitacora.perfil_permisos;
drop policy if exists perfil_permisos_update_admin on bitacora.perfil_permisos;

create policy perfil_permisos_select_self_or_admin
on bitacora.perfil_permisos
as permissive
for select
to authenticated
using (perfil_id = auth.uid() or bitacora_private.is_admin());

create policy perfil_permisos_insert_admin
on bitacora.perfil_permisos
as permissive
for insert
to authenticated
with check (bitacora_private.is_admin());

create policy perfil_permisos_update_admin
on bitacora.perfil_permisos
as permissive
for update
to authenticated
using (bitacora_private.is_admin())
with check (bitacora_private.is_admin());

alter table bitacora.requerimientos
  add column if not exists solicitante_id uuid references bitacora.perfiles(id),
  add column if not exists comprador_id uuid references bitacora.perfiles(id),
  add column if not exists supervisor_compras_id uuid references bitacora.perfiles(id),
  add column if not exists facturacion_responsable_id uuid references bitacora.perfiles(id),
  add column if not exists asignado_at timestamptz,
  add column if not exists proveedor_seleccionado text,
  add column if not exists cotizacion_estado text,
  add column if not exists orden_compra_numero text,
  add column if not exists fecha_estimada_entrega date,
  add column if not exists gestion_compras_notas text;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'bitacora.requerimientos'::regclass
      and conname = 'requerimientos_cotizacion_estado_check'
  ) then
    alter table bitacora.requerimientos
      add constraint requerimientos_cotizacion_estado_check
      check (cotizacion_estado is null or cotizacion_estado in ('Pendiente','Solicitada','Recibida','Aprobada','Rechazada'));
  end if;
end $$;

create index if not exists requerimientos_comprador_estado_idx
  on bitacora.requerimientos (comprador_id, estado);
create index if not exists requerimientos_supervisor_idx
  on bitacora.requerimientos (supervisor_compras_id);
create index if not exists requerimientos_entrega_idx
  on bitacora.requerimientos (fecha_estimada_entrega)
  where fecha_estimada_entrega is not null;

create or replace function bitacora_private.set_requerimiento_solicitante()
returns trigger
language plpgsql
security invoker
set search_path = pg_catalog, bitacora
as $$
begin
  if new.solicitante_id is null then
    new.solicitante_id := auth.uid();
  end if;
  return new;
end;
$$;

revoke all on function bitacora_private.set_requerimiento_solicitante() from public, anon, authenticated;
drop trigger if exists set_requerimiento_solicitante on bitacora.requerimientos;
create trigger set_requerimiento_solicitante
before insert on bitacora.requerimientos
for each row execute function bitacora_private.set_requerimiento_solicitante();

create table if not exists bitacora.compras_rutas (
  id bigint generated by default as identity primary key,
  nombre text not null,
  sede_id integer references bitacora.sedes(id),
  grupo_id integer references bitacora.grupos(id),
  sede_tipo text,
  texto_contiene text,
  comprador_id uuid not null references bitacora.perfiles(id),
  supervisor_id uuid references bitacora.perfiles(id),
  prioridad integer not null default 100,
  activa boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint compras_rutas_criterio_check check (
    sede_id is not null or grupo_id is not null or sede_tipo is not null or texto_contiene is not null
  )
);

alter table bitacora.compras_rutas enable row level security;
revoke all on table bitacora.compras_rutas from anon;
revoke all on table bitacora.compras_rutas from authenticated;
grant select, insert, update on table bitacora.compras_rutas to authenticated;
grant usage, select on sequence bitacora.compras_rutas_id_seq to authenticated;

drop policy if exists compras_rutas_select_staff on bitacora.compras_rutas;
drop policy if exists compras_rutas_insert_supervisor on bitacora.compras_rutas;
drop policy if exists compras_rutas_update_supervisor on bitacora.compras_rutas;

create policy compras_rutas_select_staff
on bitacora.compras_rutas
as permissive
for select
to authenticated
using (bitacora_private.is_active_profile());

create policy compras_rutas_insert_supervisor
on bitacora.compras_rutas
as permissive
for insert
to authenticated
with check (bitacora_private.has_compras_permission('supervise'));

create policy compras_rutas_update_supervisor
on bitacora.compras_rutas
as permissive
for update
to authenticated
using (bitacora_private.has_compras_permission('supervise'))
with check (bitacora_private.has_compras_permission('supervise'));

create or replace function bitacora_private.sede_in_user_scope(target_sede_id integer)
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, bitacora
as $$
  select exists (
    select 1
    from bitacora.perfiles p
    where p.id = auth.uid() and p.activo = true and (
      p.rol in ('admin','editor')
      or (p.rol in ('sede','encargado') and target_sede_id = any(coalesce(p.sede_ids, '{}'::integer[])))
      or (p.rol = 'grupo' and exists (
        select 1 from bitacora.sedes s
        where s.id = target_sede_id and s.grupo_id = p.grupo_id and s.activa = true
      ))
    )
  );
$$;

create or replace function bitacora_private.can_read_requerimiento(
  target_sede_id integer,
  target_solicitante_id uuid,
  target_comprador_id uuid,
  target_supervisor_id uuid,
  target_facturacion_id uuid
)
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, bitacora, bitacora_private
as $$
  select bitacora_private.is_active_profile() and (
    bitacora_private.is_admin_or_editor()
    or target_solicitante_id = auth.uid()
    or bitacora_private.sede_in_user_scope(target_sede_id)
    or bitacora_private.has_compras_permission('supervise')
    or (bitacora_private.has_compras_permission('manage') and (target_comprador_id is null or target_comprador_id = auth.uid()))
    or (bitacora_private.has_compras_permission('invoice') and target_facturacion_id = auth.uid())
    or target_supervisor_id = auth.uid()
  );
$$;

revoke all on function bitacora_private.sede_in_user_scope(integer) from public, anon;
revoke all on function bitacora_private.can_read_requerimiento(integer,uuid,uuid,uuid,uuid) from public, anon;
grant execute on function bitacora_private.sede_in_user_scope(integer) to authenticated;
grant execute on function bitacora_private.can_read_requerimiento(integer,uuid,uuid,uuid,uuid) to authenticated;

alter table bitacora.requerimientos enable row level security;
revoke all on table bitacora.requerimientos from anon;
revoke all on table bitacora.requerimientos from authenticated;
grant select, insert, update on table bitacora.requerimientos to authenticated;

-- Reemplazo deliberado y completo: las politicas permisivas se combinan con OR.
-- Dejarlas coexistir podria anular el nuevo alcance.
do $$
declare policy_row record;
begin
  for policy_row in
    select policyname from pg_policies
    where schemaname = 'bitacora' and tablename = 'requerimientos'
  loop
    execute format('drop policy if exists %I on bitacora.requerimientos', policy_row.policyname);
  end loop;
end $$;

create policy requerimientos_select_scoped
on bitacora.requerimientos
as permissive
for select
to authenticated
using (bitacora_private.can_read_requerimiento(
  sede_id, solicitante_id, comprador_id, supervisor_compras_id, facturacion_responsable_id
));

create policy requerimientos_insert_scoped
on bitacora.requerimientos
as permissive
for insert
to authenticated
with check (
  bitacora_private.is_active_profile()
  and (
    bitacora_private.is_admin_or_editor()
    or bitacora_private.has_compras_permission('request')
    or bitacora_private.has_compras_permission('manage')
    or bitacora_private.has_compras_permission('supervise')
    or bitacora_private.sede_in_user_scope(sede_id)
  )
  and (solicitante_id = auth.uid() or bitacora_private.is_admin_or_editor() or bitacora_private.has_compras_permission('supervise'))
);

create policy requerimientos_update_scoped
on bitacora.requerimientos
as permissive
for update
to authenticated
using (bitacora_private.can_read_requerimiento(
  sede_id, solicitante_id, comprador_id, supervisor_compras_id, facturacion_responsable_id
))
with check (bitacora_private.can_read_requerimiento(
  sede_id, solicitante_id, comprador_id, supervisor_compras_id, facturacion_responsable_id
));

create or replace function bitacora_private.protect_requerimiento_after_send()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, bitacora, bitacora_private
as $$
declare
  old_is_sent boolean := old.estado in ('Enviado','En compra','Recibido','Cumplido','Rechazado','Cancelado');
  is_buyer boolean := bitacora_private.has_compras_permission('manage')
    or bitacora_private.has_compras_permission('supervise')
    or bitacora_private.is_admin_or_editor();
  is_supervisor boolean := bitacora_private.has_compras_permission('supervise')
    or bitacora_private.is_admin_or_editor();
begin
  if new.estado is distinct from old.estado then
    if not (
      (old.estado = 'Pendiente' and new.estado in ('Observado','Aprobado','Rechazado','Cancelado'))
      or (old.estado = 'Observado' and new.estado in ('Pendiente','Rechazado','Cancelado'))
      or (old.estado = 'Aprobado' and new.estado in ('Observado','Enviado','Rechazado','Cancelado'))
      or (old.estado = 'Enviado' and new.estado in ('En compra','Recibido','Cancelado'))
      or (old.estado = 'En compra' and new.estado in ('Recibido','Cancelado'))
      or (old.estado = 'Recibido' and new.estado in ('En compra','Cumplido'))
    ) then
      raise exception 'Transicion de estado de Compras no permitida: % -> %', old.estado, new.estado;
    end if;

    if old.estado = 'Observado' and new.estado = 'Pendiente' then
      if old.solicitante_id is distinct from auth.uid() and not bitacora_private.is_purchase_approver() then
        raise exception 'Solo el solicitante o un aprobador puede reenviar un requerimiento observado';
      end if;
    elsif old.estado = 'Pendiente' and new.estado = 'Cancelado' then
      if old.solicitante_id is distinct from auth.uid() and not bitacora_private.is_purchase_approver() then
        raise exception 'Solo el solicitante o un aprobador puede cancelar el requerimiento';
      end if;
    elsif old.estado in ('Pendiente','Observado','Aprobado') then
      if not bitacora_private.is_purchase_approver() then
        raise exception 'Solo un aprobador puede realizar esta transicion';
      end if;
    elsif old.estado = 'Recibido' and new.estado = 'Cumplido' then
      if old.solicitante_id is distinct from auth.uid() and not is_buyer then
        raise exception 'Solo el solicitante o Compras puede confirmar el cumplimiento';
      end if;
    elsif not is_buyer then
      raise exception 'Solo Compras puede avanzar esta etapa';
    end if;
  end if;

  if old_is_sent and (
    new.sede_id, new.sede_nombre, new.solicitante, new.solicitante_id,
    new.cantidad, new.unidad_medida, new.descripcion, new.periodo_consumo,
    new.justificacion, new.funcion, new.sector_maquina, new.proveedor_sugerido,
    new.tipo_compra, new.urgencia, new.fecha_necesidad
  ) is distinct from (
    old.sede_id, old.sede_nombre, old.solicitante, old.solicitante_id,
    old.cantidad, old.unidad_medida, old.descripcion, old.periodo_consumo,
    old.justificacion, old.funcion, old.sector_maquina, old.proveedor_sugerido,
    old.tipo_compra, old.urgencia, old.fecha_necesidad
  ) then
    raise exception 'Los datos originales no pueden modificarse despues del envio a Compras';
  end if;

  if (
    new.comprador_id, new.supervisor_compras_id, new.facturacion_responsable_id
  ) is distinct from (
    old.comprador_id, old.supervisor_compras_id, old.facturacion_responsable_id
  ) and not is_supervisor then
    if not (
      bitacora_private.has_compras_permission('manage')
      and old.comprador_id is null
      and new.comprador_id = auth.uid()
      and new.supervisor_compras_id is not distinct from old.supervisor_compras_id
      and new.facturacion_responsable_id is not distinct from old.facturacion_responsable_id
    ) then
      raise exception 'Solo un supervisor puede asignar o reasignar responsables de Compras';
    end if;
  end if;

  if not is_buyer and (
    new.comprador_id, new.supervisor_compras_id, new.facturacion_responsable_id,
    new.proveedor_seleccionado, new.cotizacion_estado, new.orden_compra_numero,
    new.fecha_estimada_entrega, new.gestion_compras_notas
  ) is distinct from (
    old.comprador_id, old.supervisor_compras_id, old.facturacion_responsable_id,
    old.proveedor_seleccionado, old.cotizacion_estado, old.orden_compra_numero,
    old.fecha_estimada_entrega, old.gestion_compras_notas
  ) then
    raise exception 'Solo Compras puede modificar los campos de gestion';
  end if;

  return new;
end;
$$;

revoke all on function bitacora_private.protect_requerimiento_after_send() from public, anon, authenticated;
drop trigger if exists protect_requerimiento_after_send on bitacora.requerimientos;
create trigger protect_requerimiento_after_send
before update on bitacora.requerimientos
for each row execute function bitacora_private.protect_requerimiento_after_send();

comment on table bitacora.perfil_permisos is 'Permisos por modulo adicionales al rol global del perfil.';
comment on table bitacora.compras_rutas is 'Reglas configurables para sugerir comprador y supervisor segun sede o descripcion.';
comment on column bitacora.requerimientos.comprador_id is 'Comprador operativo actualmente responsable de la gestion.';
comment on column bitacora.requerimientos.fecha_estimada_entrega is 'Compromiso informado por Compras o proveedor.';

-- Validaciones manuales obligatorias antes de ejecutar COMMIT en produccion:
-- 1. anon: ningun acceso.
-- 2. sede/encargado/grupo: solo alcance territorial y pedidos propios.
-- 3. consultor sin permiso: solo pedidos propios si correspondiera.
-- 4. compras.manage: sin asignar + propios; no gestiones de otro comprador.
-- 5. compras.supervise: toda la bandeja y reasignacion.
-- 6. compras.invoice: solo registros asignados a facturacion.
-- 7. admin/editor: operacion global.

commit;
