import { useEffect,useState } from 'react'
import { Package,Plus,Printer,RefreshCw } from 'lucide-react'
import { useAuth } from '../../lib/auth'
import { cargarColaboradoresSede,cargarEpp,crearEnvioEpp,crearProductoEpp,imprimirEtiquetasEpp,urlFotoProductoEpp } from '../../lib/epp'

const emptyProduct={nombre:'',categoria:'epp',descripcion:'',talles:'',foto:null,requiere_devolucion:false,reposicion_periodica:false}
const emptyShipment={sedeId:'',bultos:1,observaciones:'',destinatarios:[]}
const prefijos={uniforme:'IND',epp:'EPP',calzado:'CAL',credencial:'CRE',otro:'OTR'}

export default function UniformesEppPanel({sedes=[]}){
  const {user,perfil}=useAuth(); const canAdmin=['admin','editor'].includes(perfil?.rol)
  const [data,setData]=useState({catalogo:[],envios:[]}); const [loading,setLoading]=useState(true); const [error,setError]=useState('')
  const [producto,setProducto]=useState(emptyProduct); const [envio,setEnvio]=useState(emptyShipment); const [selected,setSelected]=useState([])
  const [colaboradores,setColaboradores]=useState([]); const [loadingPeople,setLoadingPeople]=useState(false)
  const [fotoPreview,setFotoPreview]=useState(null); const [catalogoFotos,setCatalogoFotos]=useState({})
  const [savingShipment,setSavingShipment]=useState(false); const [success,setSuccess]=useState('')
  const load=()=>{setLoading(true);setError('');cargarEpp().then(setData).catch(e=>setError(e.message)).finally(()=>setLoading(false))}
  useEffect(load,[])
  useEffect(()=>{let active=true;Promise.all(data.catalogo.filter(x=>x.imagen_path).map(async x=>[x.id,await urlFotoProductoEpp(x.imagen_path)] )).then(rows=>{if(active)setCatalogoFotos(Object.fromEntries(rows))}).catch(()=>{});return()=>{active=false}},[data.catalogo])
  useEffect(()=>()=>{if(fotoPreview)URL.revokeObjectURL(fotoPreview)},[fotoPreview])
  const elegirFoto=file=>{if(fotoPreview)URL.revokeObjectURL(fotoPreview);setFotoPreview(file?URL.createObjectURL(file):null);setProducto(v=>({...v,foto:file||null}))}
  const saveProduct=async()=>{try{await crearProductoEpp(producto,user.id);setProducto(emptyProduct);setFotoPreview(null);await load()}catch(e){setError(e.message)}}
  const elegirSede=async sedeId=>{setEnvio({...emptyShipment,sedeId});setColaboradores([]);if(!sedeId)return;setLoadingPeople(true);try{setColaboradores(await cargarColaboradoresSede(sedeId))}catch(e){setError(e.message)}finally{setLoadingPeople(false)}}
  const togglePersona=(personaId,checked)=>setEnvio(v=>({...v,destinatarios:checked?[...v.destinatarios,{personaId,productoId:'',talle:'',cantidad:1}]:v.destinatarios.filter(x=>x.personaId!==personaId)}))
  const updatePersona=(personaId,patch)=>setEnvio(v=>({...v,destinatarios:v.destinatarios.map(x=>x.personaId===personaId?{...x,...patch}:x)}))
  const saveShipment=async()=>{setSavingShipment(true);setError('');setSuccess('');try{const creado=await crearEnvioEpp(envio,user.id);setEnvio(emptyShipment);setColaboradores([]);setSuccess(`Envío ${creado.codigo} creado correctamente.`);await load()}catch(e){setError(`No se pudo crear el envío: ${e.message}`)}finally{setSavingShipment(false)}}
  const envioValido=envio.sedeId&&envio.destinatarios.length>0&&envio.destinatarios.every(x=>x.productoId)
  const labels=data.envios.flatMap(e=>(e.epp_envio_bultos||[]).map(b=>({...b,sede:e.sede?.nombre||'Sede',total:e.epp_envio_bultos.length})))
  const print=()=>imprimirEtiquetasEpp(labels.filter(x=>selected.includes(x.id))).catch(e=>setError(e.message))
  return <div className="space-y-4">
    <div className="flex justify-between items-center"><div><h2 className="font-title font-bold" style={{color:'var(--phosphor)'}}>Uniformes y EPP</h2><p style={{color:'var(--text-dim)',fontSize:'.72rem'}}>Catálogo, envíos, destinatarios y trazabilidad por sede.</p></div><button className="btn-ghost" onClick={load}><RefreshCw size={14}/> Actualizar</button></div>
    {error&&<div className="glass p-3" style={{color:'var(--alert)'}}>{error}</div>}
    {success&&<div className="glass p-3" style={{color:'var(--phosphor)'}}>{success}</div>}
    {!canAdmin&&<div className="glass p-3" style={{color:'var(--warning)'}}>Estás usando el perfil <strong>{perfil?.rol||'sin rol'}</strong>. Podés consultar el catálogo y los bultos, pero para crear productos o envíos necesitás ingresar con un perfil administrador o editor.</div>}
    {canAdmin&&<div className="grid md:grid-cols-2 gap-4 items-start">
      <div className="glass p-4"><h3 className="font-metric mb-3">1 · CATÁLOGO</h3><div className="grid grid-cols-2 gap-2"><div className="input-dark" style={{color:'var(--text-dim)'}}>Código automático · {prefijos[producto.categoria]}-00000</div><input className="input-dark" placeholder="Nombre" value={producto.nombre} onChange={e=>setProducto({...producto,nombre:e.target.value})}/><select className="input-dark" value={producto.categoria} onChange={e=>setProducto({...producto,categoria:e.target.value})}>{['epp','uniforme','calzado','credencial','otro'].map(x=><option key={x} value={x}>{x==='uniforme'?'Indumentaria':x.toUpperCase()}</option>)}</select><input className="input-dark" placeholder="Talles: S, M, L, XL" value={producto.talles} onChange={e=>setProducto({...producto,talles:e.target.value})}/></div><textarea className="input-dark w-full mt-2" placeholder="Descripción" value={producto.descripcion} onChange={e=>setProducto({...producto,descripcion:e.target.value})}/><label className="btn-ghost mt-2" style={{display:'inline-flex',cursor:'pointer'}}>Agregar foto<input type="file" accept="image/jpeg,image/png,image/webp" hidden onChange={e=>elegirFoto(e.target.files?.[0])}/></label>{fotoPreview&&<img src={fotoPreview} alt="Vista previa del producto" className="mt-2" style={{width:120,height:120,objectFit:'cover',border:'1px solid rgba(255,255,255,.15)'}}/>}<button className="btn-primary mt-2 ml-2" disabled={!producto.nombre} onClick={saveProduct}><Plus size={13}/> Crear producto</button></div>
      <div className="glass p-4"><h3 className="font-metric mb-3">2 · NUEVO ENVÍO POR SEDE</h3><select className="input-dark w-full" value={envio.sedeId} onChange={e=>elegirSede(e.target.value)}><option value="">Elegir sede...</option>{sedes.map(s=><option key={s.id} value={s.id}>{s.nombre}</option>)}</select><div className="grid grid-cols-2 gap-2 mt-2"><label><small>Cantidad de bultos</small><input className="input-dark w-full" type="number" min="1" value={envio.bultos} onChange={e=>setEnvio({...envio,bultos:e.target.value})}/></label><textarea className="input-dark" placeholder="Observaciones" value={envio.observaciones} onChange={e=>setEnvio({...envio,observaciones:e.target.value})}/></div>{envio.sedeId&&<div className="mt-3"><div className="font-metric mb-2">DESTINATARIOS · {loadingPeople?'Cargando...':`${colaboradores.length} colaboradores activos`}</div><div className="space-y-2" style={{maxHeight:280,overflow:'auto'}}>{colaboradores.map(p=>{const item=envio.destinatarios.find(x=>x.personaId===p.id);const prod=data.catalogo.find(x=>x.id===item?.productoId);return <div key={p.id} className="p-2" style={{border:'1px solid rgba(255,255,255,.1)'}}><label className="flex items-center gap-2"><input type="checkbox" checked={!!item} onChange={e=>togglePersona(p.id,e.target.checked)}/><strong>{p.apellido}, {p.nombre}</strong><small style={{color:'var(--text-dim)'}}>{p.puesto||''}</small></label>{item&&<div className="grid grid-cols-3 gap-2 mt-2">{catalogoFotos[prod?.id]&&<img src={catalogoFotos[prod.id]} alt={prod.nombre} style={{width:44,height:44,objectFit:'cover'}}/>}<select className="input-dark" value={item.productoId} onChange={e=>updatePersona(p.id,{productoId:e.target.value,talle:''})}><option value="">Producto...</option>{data.catalogo.map(x=><option key={x.id} value={x.id}>{x.codigo} · {x.nombre}</option>)}</select><select className="input-dark" value={item.talle} onChange={e=>updatePersona(p.id,{talle:e.target.value})}><option value="">Sin talle</option>{(prod?.epp_catalogo_talles||[]).map(t=><option key={t.id} value={t.talle}>{t.talle}</option>)}</select><input className="input-dark" aria-label="Cantidad" type="number" min="1" value={item.cantidad} onChange={e=>updatePersona(p.id,{cantidad:e.target.value})}/></div>}</div>})}</div></div>}<button className="btn-primary mt-3" disabled={!envioValido||savingShipment} onClick={saveShipment}><Package size={13}/> {savingShipment?'Creando envío...':'Crear envío, asignaciones y bultos'}</button></div>
    </div>}
    {!canAdmin&&<div className="glass p-4"><h3 className="font-metric mb-3">CATÁLOGO · {data.catalogo.length} PRODUCTOS</h3>{loading?<p>Cargando...</p>:!data.catalogo.length?<p style={{color:'var(--text-dim)'}}>Todavía no hay productos cargados.</p>:<div className="grid md:grid-cols-3 gap-3">{data.catalogo.map(x=><div key={x.id} className="p-3 flex gap-3" style={{border:'1px solid rgba(255,255,255,.1)'}}>{catalogoFotos[x.id]?<img src={catalogoFotos[x.id]} alt={x.nombre} style={{width:72,height:72,objectFit:'cover'}}/>:<div style={{width:72,height:72,display:'grid',placeItems:'center',border:'1px solid rgba(255,255,255,.1)',color:'var(--text-dim)'}}>Sin foto</div>}<div><strong>{x.nombre}</strong><br/><small>{x.codigo} · {x.categoria}</small><br/><small style={{color:'var(--text-dim)'}}>{(x.epp_catalogo_talles||[]).map(t=>t.talle).join(', ')||'Sin talle'}</small></div></div>)}</div>}</div>}
    <div className="glass p-4"><div className="flex justify-between items-center mb-3"><h3 className="font-metric">BULTOS PARA IMPRIMIR</h3><button className="btn-primary" disabled={!selected.length} onClick={print}><Printer size={13}/> Imprimir seleccionados ({selected.length})</button></div>{loading?<p>Cargando...</p>:!labels.length?<p style={{color:'var(--text-dim)'}}>Todavía no hay bultos.</p>:<div className="grid md:grid-cols-3 gap-2">{labels.map(b=><label key={b.id} className="p-3 flex gap-2" style={{border:'1px solid rgba(255,255,255,.1)'}}><input type="checkbox" checked={selected.includes(b.id)} onChange={e=>setSelected(v=>e.target.checked?[...v,b.id]:v.filter(id=>id!==b.id))}/><span><strong>{b.codigo}</strong><br/><small>{b.sede} · Bulto {b.numero}/{b.total}</small></span></label>)}</div>}</div>
  </div>
}
