import React from 'react'
import { fireEvent, render, screen, waitFor, cleanup } from '@testing-library/react'
import { afterEach, beforeEach, describe, it, expect, vi } from 'vitest'
import Articulos from './Articulos'
import { productResolver, saveProduct, enrichProduct, recordBarcodeSearch, listKioskSites, loadProductSiteSettings, saveProductSiteSetting, listProductMasterValues, saveProductMasterValue } from '../lib/productQueries'

const authState = vi.hoisted(() => ({ rol:null }))
vi.mock('../lib/auth', () => ({ useAuth:() => ({ can:() => true, perfil:{ nombre:'Prueba', rol:authState.rol } }) }))
vi.mock('../lib/adjuntos', () => ({ uploadAdjunto:vi.fn() }))
vi.mock('../components/ProductBarcodeScanner', () => ({ default:() => <div>Lector listo</div> }))
vi.mock('../lib/productQueries', () => ({ productResolver:{ resolve:vi.fn() }, findProduct:vi.fn(), findProductById:vi.fn(), saveProduct:vi.fn(), enrichProduct:vi.fn(), searchProducts:vi.fn().mockResolvedValue([]), validateProduct:vi.fn(), recordBarcodeSearch:vi.fn().mockResolvedValue(), listKioskSites:vi.fn().mockResolvedValue([]), loadProductSiteSettings:vi.fn().mockResolvedValue([]), saveProductSiteSetting:vi.fn(), listProductMasterValues:vi.fn(), saveProductMasterValue:vi.fn() }))
beforeEach(() => { vi.clearAllMocks(); authState.rol = null; listProductMasterValues.mockResolvedValue([{ id:'b1',kind:'brand',name:'Marca prueba',active:true },{ id:'u1',kind:'stock_unit',name:'unidad',active:true }]) })
afterEach(cleanup)
describe('flujo artículos', () => {
  it('permite volver al inicio desde el maestro de artículos', () => {
    const onNavigate = vi.fn()
    render(<Articulos onNavigate={onNavigate} />)
    fireEvent.click(screen.getByRole('button', { name:'Volver atrás' }))
    expect(onNavigate).toHaveBeenCalledWith('inicio')
  })
  it('da al usuario de depósito el relevamiento y el maestro completo', async () => {
    authState.rol = 'deposito'
    render(<Articulos initialMode="list" />)
    expect(screen.getByLabelText('Escaneá con pistola o ingresá el código manualmente')).toHaveFocus()
    expect(screen.getByRole('button', { name:'ESCANEAR CÓDIGO' })).toBeInTheDocument()
    expect(screen.getByRole('button', { name:'Volver atrás' })).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name:'Artículos' }))
    expect(await screen.findByText('Descargar base en Excel')).toBeInTheDocument()
  })
  it('presenta propuestas antes de aplicar y conserva los datos corregidos', async () => {
    productResolver.resolve.mockResolvedValue({ product:{ name:'Mi azúcar',brand:'Mi marca' },origin:'external',warnings:[] })
    enrichProduct.mockResolvedValue({ products:[{ name:'Nombre externo',brand:'Marca externa',category:'Azúcares',net_quantity:1,net_unit:'kg',source:{ provider:'Open Food Facts',source_url:'https://world.openfoodfacts.org/product/012345678905',retrieved_at:'2026-09-07T12:00:00Z' } }],warnings:[] })
    render(<Articulos initialMode="scan" />)
    fireEvent.change(screen.getByLabelText('Escaneá con pistola o ingresá el código manualmente'),{ target:{ value:'012345678905' } })
    fireEvent.click(screen.getByRole('button',{ name:'Buscar',exact:true }))
    await screen.findByDisplayValue('Mi azúcar')
    fireEvent.click(screen.getByRole('button',{name:'Completar datos faltantes'}))
    await screen.findByText('Datos propuestos')
    expect(screen.getByLabelText('Categoría')).toHaveValue('')
    fireEvent.click(screen.getByRole('button',{name:'Aplicar datos propuestos'}))
    expect(screen.getByLabelText('Categoría')).toHaveValue('Azúcares')
    expect(screen.getByLabelText(/^Marca \*/)).toHaveValue('Mi marca')
    expect(saveProduct).not.toHaveBeenCalled()
  })
  it('permite completar un desconocido, guardar y pasar al siguiente', async () => {
    productResolver.resolve.mockResolvedValue({ product:null, origin:'unknown', warnings:[] })
    saveProduct.mockImplementation(async form => ({ ...form, expected_updated_at:'2026-09-07T12:00:00Z' }))
    render(<Articulos initialMode="scan" />)
    fireEvent.change(screen.getByLabelText('Escaneá con pistola o ingresá el código manualmente'), { target:{ value:'012345678905' } })
    fireEvent.click(screen.getByRole('button', { name:'Buscar', exact:true }))
    await screen.findByText('Producto no identificado')
    expect(recordBarcodeSearch).toHaveBeenCalledWith(expect.objectContaining({ barcode:'012345678905',found:false,sourceCode:'NOT_FOUND' }))
    fireEvent.change(screen.getByLabelText('Nombre del artículo *'), { target:{ value:'Artículo de prueba' } })
    fireEvent.change(screen.getByLabelText(/^Marca \*/), { target:{ value:'Marca prueba' } })
    fireEvent.change(screen.getByLabelText(/^Unidad base de stock \*/), { target:{ value:'unidad' } })
    fireEvent.change(screen.getByLabelText('Nivel de empaque *'), { target:{ value:'case' } })
    fireEvent.change(screen.getByLabelText('Contenido por unidad contenida *'), { target:{ value:'8' } })
    fireEvent.change(screen.getByLabelText('Unidad de contenido *'), { target:{ value:'g' } })
    fireEvent.change(screen.getByLabelText('Unidades contenidas por caja / bulto'), { target:{ value:'192' } })
    fireEvent.click(screen.getByRole('button', { name:'GUARDAR Y ESCANEAR SIGUIENTE' }))
    const codeInput = await screen.findByLabelText('Escaneá con pistola o ingresá el código manualmente')
    expect(codeInput).toHaveValue('')
    expect(codeInput).toHaveFocus()
    expect(screen.getByRole('button', { name:'ESCANEAR CÓDIGO' })).toBeInTheDocument()
    expect(screen.queryByText('Lector listo')).not.toBeInTheDocument()
    expect(saveProduct.mock.calls[0][0]).toMatchObject({ barcode:'012345678905', name:'Artículo de prueba', net_quantity:'8', units_per_package:'192', packaging_level:'case' })
  })
  it('vacía y vuelve a enfocar la entrada si una lectura de pistola no puede consultarse', async () => {
    productResolver.resolve.mockRejectedValue(new Error('Sin conexión'))
    render(<Articulos initialMode="scan" />)
    const codeInput = screen.getByLabelText('Escaneá con pistola o ingresá el código manualmente')
    expect(codeInput).toHaveFocus()
    fireEvent.change(codeInput, { target:{ value:'012345678905' } })
    fireEvent.submit(codeInput.closest('form'))
    await screen.findByText('Sin conexión')
    expect(codeInput).toHaveValue('')
    expect(codeInput).toHaveFocus()
  })
  it('conserva el formulario y no avanza si el guardado falla', async () => {
    productResolver.resolve.mockResolvedValue({ product:null, origin:'unknown', warnings:[] })
    saveProduct.mockRejectedValue(new Error('Sin conexión'))
    render(<Articulos initialMode="scan" />)
    fireEvent.change(screen.getByLabelText('Escaneá con pistola o ingresá el código manualmente'), { target:{ value:'012345678905' } })
    fireEvent.click(screen.getByRole('button', { name:'Buscar', exact:true }))
    await screen.findByText('Producto no identificado')
    fireEvent.change(screen.getByLabelText('Nombre del artículo *'), { target:{ value:'Se conserva' } })
    fireEvent.change(screen.getByLabelText(/^Marca \*/), { target:{ value:'Marca prueba' } })
    fireEvent.change(screen.getByLabelText(/^Unidad base de stock \*/), { target:{ value:'unidad' } })
    fireEvent.change(screen.getByLabelText('Nivel de empaque *'), { target:{ value:'unit' } })
    fireEvent.change(screen.getByLabelText('Contenido por unidad contenida *'), { target:{ value:'1' } })
    fireEvent.change(screen.getByLabelText('Unidad de contenido *'), { target:{ value:'unidad' } })
    fireEvent.click(screen.getByRole('button', { name:'GUARDAR Y ESCANEAR SIGUIENTE' }))
    await screen.findByText('Sin conexión')
    expect(screen.getByLabelText('Nombre del artículo *')).toHaveValue('Se conserva')
    expect(screen.queryByText('Lector listo')).not.toBeInTheDocument()
  })
  it('configura precio y mínimo de forma independiente para una sede Kiosco asignada', async () => {
    listKioskSites.mockResolvedValue([{ id:7,nombre:'Sede Rosario',tipo:'Comedor' }])
    loadProductSiteSettings.mockResolvedValue([{ sede_id:7,product_id:'p1',presentation_id:'pr1',sale_price:3000,reference_cost:2000,stock_minimum:4,currency:'ARS',active:true }])
    saveProductSiteSetting.mockResolvedValue({ sede_id:7,product_id:'p1',presentation_id:'pr1',sale_price:3200,reference_cost:2000,stock_minimum:5,currency:'ARS',active:true })
    productResolver.resolve.mockResolvedValue({ origin:'local',warnings:[],product:{ product_id:'p1',presentation_id:'pr1',expected_updated_at:'2026-09-16T12:00:00Z',name:'Coca Cola 500 ml',barcode:'012345678905',stock_unit:'unidad',stock_factor:1,status:'verified',related_barcodes:[] } })
    render(<Articulos initialMode="scan" />)
    fireEvent.change(screen.getByLabelText('Escaneá con pistola o ingresá el código manualmente'),{ target:{ value:'012345678905' } })
    fireEvent.click(screen.getByRole('button',{name:'Buscar',exact:true}))
    await screen.findByText('Sede Rosario')
    fireEvent.change(screen.getByLabelText('Precio de venta'),{ target:{ value:'3200' } })
    fireEvent.change(screen.getByLabelText('Stock mínimo'),{ target:{ value:'5' } })
    fireEvent.click(screen.getByRole('button',{name:'Guardar precio'}))
    await waitFor(() => expect(saveProductSiteSetting).toHaveBeenCalledWith(expect.objectContaining({ sede_id:7,product_id:'p1',presentation_id:'pr1',sale_price:'3200',stock_minimum:'5',active:true })))
  })
  it('abre y guarda una ficha manual sin exigir código de barras', async () => {
    saveProduct.mockImplementation(async form => ({ ...form, internal_code:'ART-000010', presentation_id:'pr10', expected_updated_at:'2026-09-21T12:00:00Z' }))
    render(<Articulos />)
    fireEvent.click(screen.getByRole('button', { name:'Agregar artículo' }))
    await screen.findByRole('option', { name:'Marca prueba' })
    expect(screen.getByText('Sin código de barras')).toBeInTheDocument()
    fireEvent.change(screen.getByLabelText('Nombre del artículo *'), { target:{ value:'Vaso descartable' } })
    fireEvent.change(screen.getByLabelText(/^Marca \*/), { target:{ value:'Marca prueba' } })
    fireEvent.change(screen.getByLabelText(/^Unidad base de stock \*/), { target:{ value:'unidad' } })
    fireEvent.change(screen.getByLabelText('Nivel de empaque *'), { target:{ value:'unit' } })
    fireEvent.change(screen.getByLabelText('Contenido por unidad contenida *'), { target:{ value:'1' } })
    fireEvent.change(screen.getByLabelText('Unidad de contenido *'), { target:{ value:'unidad' } })
    fireEvent.click(screen.getByRole('button', { name:'GUARDAR ARTÍCULO' }))
    await waitFor(() => expect(saveProduct).toHaveBeenCalledWith(expect.objectContaining({ barcode:'', name:'Vaso descartable', brand:'Marca prueba', net_quantity:'1', net_unit:'unidad' })))
  })
  it('asocia ingrediente del maestro y completa su unidad de contenido', async () => {
    listProductMasterValues.mockResolvedValue([
      { id:'b1',kind:'brand',name:'Marca prueba',active:true },
      { id:'u1',kind:'stock_unit',name:'unidad',active:true },
      { id:'c1',kind:'category',name:'Harinas',active:true },
      { id:'s1',kind:'subcategory',name:'Trigo',parent_id:'c1',active:true },
      { id:'i1',kind:'ingredient',name:'Harina 000',unit:'kg',active:true },
      { id:'p1',kind:'presentation',name:'Bolsa 1 kg',active:true },
    ])
    saveProduct.mockImplementation(async form => ({ ...form, expected_updated_at:'2026-09-27T12:00:00Z' }))
    render(<Articulos />)
    fireEvent.click(screen.getByRole('button', { name:'Agregar artículo' }))
    await screen.findByRole('option', { name:'Harina 000 · kg' })
    fireEvent.change(screen.getByLabelText('Nombre del artículo *'), { target:{ value:'Harina Morixe 000' } })
    fireEvent.change(screen.getByLabelText(/^Marca \*/), { target:{ value:'Marca prueba' } })
    fireEvent.change(screen.getByLabelText('Categoría'), { target:{ value:'Harinas' } })
    fireEvent.change(screen.getByLabelText('Subcategoría'), { target:{ value:'Trigo' } })
    fireEvent.change(screen.getByLabelText(/^Ingrediente asociado/), { target:{ value:'i1' } })
    expect(screen.getByLabelText(/^Unidad de contenido \*/)).toHaveValue('kg')
    expect(screen.getByLabelText(/^Unidad de contenido \*/)).toBeDisabled()
    fireEvent.change(screen.getByLabelText('Presentación / descripción del envase'), { target:{ value:'Bolsa 1 kg' } })
    fireEvent.change(screen.getByLabelText(/^Unidad base de stock \*/), { target:{ value:'unidad' } })
    fireEvent.change(screen.getByLabelText('Nivel de empaque *'), { target:{ value:'unit' } })
    fireEvent.change(screen.getByLabelText('Contenido por unidad contenida *'), { target:{ value:'1' } })
    fireEvent.click(screen.getByRole('button', { name:'GUARDAR ARTÍCULO' }))
    await waitFor(() => expect(saveProduct).toHaveBeenCalledWith(expect.objectContaining({ category:'Harinas',subcategory:'Trigo',ingredient_master_id:'i1',presentation:'Bolsa 1 kg',net_unit:'kg' })))
  })
  it('requiere categoría para la subcategoría y unidad para el ingrediente del maestro', async () => {
    render(<Articulos />)
    fireEvent.click(screen.getByRole('button', { name:'Maestros' }))
    fireEvent.change(screen.getByLabelText('Nueva opción de Subcategorías'), { target:{ value:'Trigo' } })
    const subForm = screen.getByLabelText('Nueva opción de Subcategorías').closest('form')
    expect(subForm.querySelector('button[type="submit"]')).toBeDisabled()
    fireEvent.change(screen.getByLabelText('Nueva opción de Ingredientes'), { target:{ value:'Harina 000' } })
    const ingredientForm = screen.getByLabelText('Nueva opción de Ingredientes').closest('form')
    expect(ingredientForm.querySelector('button[type="submit"]')).toBeDisabled()
    fireEvent.change(screen.getByLabelText('Unidad del nuevo ingrediente'), { target:{ value:'kg' } })
    fireEvent.submit(ingredientForm)
    await waitFor(() => expect(saveProductMasterValue).toHaveBeenCalledWith(expect.objectContaining({ kind:'ingredient',name:'Harina 000',unit:'kg' })))
  })
})
