import React from 'react'
import { fireEvent, render, screen, waitFor, cleanup } from '@testing-library/react'
import { afterEach, beforeEach, describe, it, expect, vi } from 'vitest'
import Articulos from './Articulos'
import { productResolver, saveProduct, enrichProduct, recordBarcodeSearch } from '../lib/productQueries'

const authState = vi.hoisted(() => ({ rol:null }))
vi.mock('../lib/auth', () => ({ useAuth:() => ({ can:() => true, perfil:{ nombre:'Prueba', rol:authState.rol } }) }))
vi.mock('../lib/adjuntos', () => ({ uploadAdjunto:vi.fn() }))
vi.mock('../components/ProductBarcodeScanner', () => ({ default:() => <div>Lector listo</div> }))
vi.mock('../lib/productQueries', () => ({ productResolver:{ resolve:vi.fn() }, findProduct:vi.fn(), saveProduct:vi.fn(), enrichProduct:vi.fn(), searchProducts:vi.fn().mockResolvedValue([]), validateProduct:vi.fn(), recordBarcodeSearch:vi.fn().mockResolvedValue() }))
beforeEach(() => { vi.clearAllMocks(); authState.rol = null })
afterEach(cleanup)
describe('flujo artículos', () => {
  it('permite volver al inicio desde el maestro de artículos', () => {
    const onNavigate = vi.fn()
    render(<Articulos onNavigate={onNavigate} />)
    fireEvent.click(screen.getByRole('button', { name:'Volver atrás' }))
    expect(onNavigate).toHaveBeenCalledWith('inicio')
  })
  it('da al usuario de depósito el relevamiento y el maestro completo', async () => {
    authState.rol = 'deposito'
    render(<Articulos initialMode="list" />)
    expect(screen.getByLabelText('Escaneá con pistola o ingresá el código manualmente')).toHaveFocus()
    expect(screen.getByRole('button', { name:'ESCANEAR CÓDIGO' })).toBeInTheDocument()
    expect(screen.getByRole('button', { name:'Volver atrás' })).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name:'Artículos' }))
    expect(await screen.findByText('Descargar base en Excel')).toBeInTheDocument()
  })
  it('presenta propuestas antes de aplicar y conserva los datos corregidos', async () => {
    productResolver.resolve.mockResolvedValue({ product:{ name:'Mi azúcar',brand:'Mi marca' },origin:'external',warnings:[] })
    enrichProduct.mockResolvedValue({ products:[{ name:'Nombre externo',brand:'Marca externa',category:'Azúcares',net_quantity:1,net_unit:'kg',source:{ provider:'Open Food Facts',source_url:'https://world.openfoodfacts.org/product/012345678905',retrieved_at:'2026-09-07T12:00:00Z' } }],warnings:[] })
    render(<Articulos initialMode="scan" />)
    fireEvent.change(screen.getByLabelText('Escaneá con pistola o ingresá el código manualmente'),{ target:{ value:'012345678905' } })
    fireEvent.click(screen.getByRole('button',{ name:'Buscar',exact:true }))
    await screen.findByDisplayValue('Mi azúcar')
    fireEvent.click(screen.getByRole('button',{name:'Completar datos faltantes'}))
    await screen.findByText('Datos propuestos')
    expect(screen.getByLabelText('Categoría')).toHaveValue('')
    fireEvent.click(screen.getByRole('button',{name:'Aplicar datos propuestos'}))
    expect(screen.getByLabelText('Categoría')).toHaveValue('Azúcares')
    expect(screen.getByLabelText('Marca')).toHaveValue('Mi marca')
    expect(saveProduct).not.toHaveBeenCalled()
  })
  it('permite completar un desconocido, guardar y pasar al siguiente', async () => {
    productResolver.resolve.mockResolvedValue({ product:null, origin:'unknown', warnings:[] })
    saveProduct.mockImplementation(async form => ({ ...form, expected_updated_at:'2026-09-07T12:00:00Z' }))
    render(<Articulos initialMode="scan" />)
    fireEvent.change(screen.getByLabelText('Escaneá con pistola o ingresá el código manualmente'), { target:{ value:'012345678905' } })
    fireEvent.click(screen.getByRole('button', { name:'Buscar', exact:true }))
    await screen.findByText('Producto no identificado')
    expect(recordBarcodeSearch).toHaveBeenCalledWith(expect.objectContaining({ barcode:'012345678905',found:false,sourceCode:'NOT_FOUND' }))
    fireEvent.change(screen.getByLabelText('Nombre del artículo *'), { target:{ value:'Artículo de prueba' } })
    fireEvent.change(screen.getByLabelText('Nivel de empaque'), { target:{ value:'case' } })
    fireEvent.change(screen.getByLabelText('Contenido por unidad contenida'), { target:{ value:'8' } })
    fireEvent.change(screen.getByLabelText('Unidad de contenido'), { target:{ value:'g' } })
    fireEvent.change(screen.getByLabelText('Unidades contenidas por caja / bulto'), { target:{ value:'192' } })
    fireEvent.click(screen.getByRole('button', { name:'GUARDAR Y ESCANEAR SIGUIENTE' }))
    const codeInput = await screen.findByLabelText('Escaneá con pistola o ingresá el código manualmente')
    expect(codeInput).toHaveValue('')
    expect(codeInput).toHaveFocus()
    expect(screen.getByRole('button', { name:'ESCANEAR CÓDIGO' })).toBeInTheDocument()
    expect(screen.queryByText('Lector listo')).not.toBeInTheDocument()
    expect(saveProduct.mock.calls[0][0]).toMatchObject({ barcode:'012345678905', name:'Artículo de prueba', net_quantity:'8', units_per_package:'192', packaging_level:'case' })
  })
  it('vacía y vuelve a enfocar la entrada si una lectura de pistola no puede consultarse', async () => {
    productResolver.resolve.mockRejectedValue(new Error('Sin conexión'))
    render(<Articulos initialMode="scan" />)
    const codeInput = screen.getByLabelText('Escaneá con pistola o ingresá el código manualmente')
    expect(codeInput).toHaveFocus()
    fireEvent.change(codeInput, { target:{ value:'012345678905' } })
    fireEvent.submit(codeInput.closest('form'))
    await screen.findByText('Sin conexión')
    expect(codeInput).toHaveValue('')
    expect(codeInput).toHaveFocus()
  })
  it('conserva el formulario y no avanza si el guardado falla', async () => {
    productResolver.resolve.mockResolvedValue({ product:null, origin:'unknown', warnings:[] })
    saveProduct.mockRejectedValue(new Error('Sin conexión'))
    render(<Articulos initialMode="scan" />)
    fireEvent.change(screen.getByLabelText('Escaneá con pistola o ingresá el código manualmente'), { target:{ value:'012345678905' } })
    fireEvent.click(screen.getByRole('button', { name:'Buscar', exact:true }))
    await screen.findByText('Producto no identificado')
    fireEvent.change(screen.getByLabelText('Nombre del artículo *'), { target:{ value:'Se conserva' } })
    fireEvent.click(screen.getByRole('button', { name:'GUARDAR Y ESCANEAR SIGUIENTE' }))
    await screen.findByText('Sin conexión')
    expect(screen.getByLabelText('Nombre del artículo *')).toHaveValue('Se conserva')
    expect(screen.queryByText('Lector listo')).not.toBeInTheDocument()
  })
})
