-- Autorizada por el usuario el 2026-08-12.
-- Proyecto destino exclusivo: mixyhfdlzjarvszinytk (cerdova-db).
-- Certificados y respaldos sensibles vinculados a bitacora.persona_novedades.

create table if not exists equipo.ausencia_documentos (
  id bigint generated by default as identity primary key,
  persona_novedad_id bigint not null references bitacora.persona_novedades(id) on delete cascade,
  persona_id uuid not null references equipo.personas(id) on delete cascade,
  nombre text not null,
  storage_path text not null unique,
  mime_type text,
  tamano_bytes bigint,
  uploaded_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

alter table equipo.ausencia_documentos enable row level security;

grant select, insert on equipo.ausencia_documentos to authenticated;

drop policy if exists ausencia_documentos_select_scoped on equipo.ausencia_documentos;
create policy ausencia_documentos_select_scoped
on equipo.ausencia_documentos
for select to authenticated
using (
  exists (
    select 1
    from bitacora.perfiles p
    join bitacora.persona_novedades n on n.id = ausencia_documentos.persona_novedad_id
    where p.id = (select auth.uid())
      and p.activo = true
      and (
        p.rol in ('admin', 'editor')
        or (p.rol = 'grupo' and exists (
          select 1 from bitacora.sedes s
          where s.id = n.sede_id and s.grupo_id = p.grupo_id
        ))
        or (p.rol = 'encargado' and n.sede_id = any(coalesce(p.sede_ids, '{}'::integer[])))
      )
  )
);

drop policy if exists ausencia_documentos_insert_scoped on equipo.ausencia_documentos;
create policy ausencia_documentos_insert_scoped
on equipo.ausencia_documentos
for insert to authenticated
with check (
  uploaded_by = (select auth.uid())
  and exists (
    select 1
    from bitacora.perfiles p
    join bitacora.persona_novedades n on n.id = ausencia_documentos.persona_novedad_id
    where p.id = (select auth.uid())
      and p.activo = true
      and n.persona_id = ausencia_documentos.persona_id
      and (
        p.rol in ('admin', 'editor')
        or (p.rol = 'grupo' and exists (
          select 1 from bitacora.sedes s
          where s.id = n.sede_id and s.grupo_id = p.grupo_id
        ))
        or (p.rol in ('encargado', 'sede') and n.sede_id = any(coalesce(p.sede_ids, '{}'::integer[])))
      )
  )
);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'certificados-ausentismo',
  'certificados-ausentismo',
  false,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp', 'application/pdf']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists certificados_ausentismo_insert_scoped on storage.objects;
create policy certificados_ausentismo_insert_scoped
on storage.objects
for insert to authenticated
with check (
  bucket_id = 'certificados-ausentismo'
  and (storage.foldername(name))[1] = 'persona_novedades'
  and exists (
    select 1
    from bitacora.perfiles p
    join bitacora.persona_novedades n
      on n.id::text = (storage.foldername(name))[2]
    where p.id = (select auth.uid())
      and p.activo = true
      and (
        p.rol in ('admin', 'editor')
        or (p.rol = 'grupo' and exists (
          select 1 from bitacora.sedes s
          where s.id = n.sede_id and s.grupo_id = p.grupo_id
        ))
        or (p.rol in ('encargado', 'sede') and n.sede_id = any(coalesce(p.sede_ids, '{}'::integer[])))
      )
  )
);

drop policy if exists certificados_ausentismo_select_scoped on storage.objects;
create policy certificados_ausentismo_select_scoped
on storage.objects
for select to authenticated
using (
  bucket_id = 'certificados-ausentismo'
  and (storage.foldername(name))[1] = 'persona_novedades'
  and exists (
    select 1
    from bitacora.perfiles p
    join bitacora.persona_novedades n
      on n.id::text = (storage.foldername(name))[2]
    where p.id = (select auth.uid())
      and p.activo = true
      and (
        p.rol in ('admin', 'editor')
        or (p.rol = 'grupo' and exists (
          select 1 from bitacora.sedes s
          where s.id = n.sede_id and s.grupo_id = p.grupo_id
        ))
        or (p.rol = 'encargado' and n.sede_id = any(coalesce(p.sede_ids, '{}'::integer[])))
      )
  )
);

comment on table equipo.ausencia_documentos is
  'Metadatos de certificados y respaldos privados asociados a ausencias de personal.';
