-- Importación de maestros POLARIS. Ejecutar solamente después de 20260927222116_article_taxonomy_ingredient_master.sql.

-- Fuente: itemcategory(1).xls, item_presentacion.xls y marca(1).xls provistos por el usuario.

-- Idempotente: conserva los valores existentes y omite nombres ya registrados sin reemplazarlos.

-- Los códigos de categoría del archivo se documentan abajo; product_master_values no tiene columna de código.

-- ALM: ALMACEN

-- CAR: CARNES

-- FYV: FRUTAS Y VERDURAS

-- REC: RECETAS

-- CON: CONGELADOS

-- LIM: LIMPIEZA

-- Se omitieron 7 filas duplicadas de marca y 1 fila duplicada de presentación.

begin;

insert into bitacora.product_master_values(kind,name) values
  ('category','ALMACEN'),
  ('category','CARNES'),
  ('category','FRUTAS Y VERDURAS'),
  ('category','RECETAS'),
  ('category','CONGELADOS'),
  ('category','LIMPIEZA')
on conflict do nothing;

insert into bitacora.product_master_values(kind,name) values
  ('presentation','BIDON'),
  ('presentation','BLISTER'),
  ('presentation','BOLSA'),
  ('presentation','BOTELLA'),
  ('presentation','CABEZA'),
  ('presentation','CAJA'),
  ('presentation','DOCENA'),
  ('presentation','FRASCO'),
  ('presentation','KILO'),
  ('presentation','LATA'),
  ('presentation','LITRO'),
  ('presentation','PACK'),
  ('presentation','PAQUETE'),
  ('presentation','PLANCHA'),
  ('presentation','POMO'),
  ('presentation','ROLLO'),
  ('presentation','SACHET'),
  ('presentation','TETRA'),
  ('presentation','UNIDAD'),
  ('presentation','DOY'),
  ('presentation','BALDE'),
  ('presentation','POTE'),
  ('presentation','BANDEJA'),
  ('presentation','CAJON'),
  ('presentation','METRO'),
  ('presentation','HORA')
on conflict do nothing;

insert into bitacora.product_master_values(kind,name) values
  ('brand','MOLTO'),
  ('brand','MAROLIO'),
  ('brand','COCINERO'),
  ('brand','YANCANELO'),
  ('brand','ABEDUL'),
  ('brand','NATURA'),
  ('brand','HELLMANNS'),
  ('brand','CONRAY'),
  ('brand','FANACOA'),
  ('brand','SAVORA'),
  ('brand','DOS ANCLAS'),
  ('brand','AGUILA'),
  ('brand','KEUKEN'),
  ('brand','KNORR'),
  ('brand','LA POSTA DEL OLIVO'),
  ('brand','BODEGA PRIVADA'),
  ('brand','EL SUPREMO'),
  ('brand','BAGGIO DE LA HUERTA'),
  ('brand','7 DIAS'),
  ('brand','CADA DIA'),
  ('brand','LA CAMPAGNOLA'),
  ('brand','LAGRIMAS DEL SOL'),
  ('brand','ARCOR S.A.I.C.'),
  ('brand','MARVAVIC'),
  ('brand','REYGAL'),
  ('brand','CUMANA'),
  ('brand','DELICIAS MARINAS'),
  ('brand','DOS HERMANOS'),
  ('brand','GALLO'),
  ('brand','VANGUARDIA'),
  ('brand','DICOMERE'),
  ('brand','INALPA'),
  ('brand','ADENOMAR'),
  ('brand','EL DIQUE'),
  ('brand','QUAKER'),
  ('brand','SELCA'),
  ('brand','LEDESMA'),
  ('brand','FELFORT'),
  ('brand','LA BANDA'),
  ('brand','NESQUIK'),
  ('brand','OYAMBRE'),
  ('brand','BONAFIDE'),
  ('brand','NOBLEZA'),
  ('brand','EMETH'),
  ('brand','BIG CHEESE'),
  ('brand','LA PAULINA'),
  ('brand','SAN REMO'),
  ('brand','MAIZENA'),
  ('brand','KESKY'),
  ('brand','RAVANA'),
  ('brand','ALZOL'),
  ('brand','REINHARINA'),
  ('brand','DEL CAMPO'),
  ('brand','CLIGHT'),
  ('brand','TANG'),
  ('brand','KRACHITOS'),
  ('brand','LEVEX'),
  ('brand','RAMONEDA'),
  ('brand','MONTE VIEJO'),
  ('brand','COPETIN'),
  ('brand','LA CAMPAGNOLA S.A.C.I.'),
  ('brand','ACAPULCO'),
  ('brand','PUMPER'),
  ('brand','GODET'),
  ('brand','EXQUISITA'),
  ('brand','GLUTAL'),
  ('brand','ELIO'),
  ('brand','BAGLEY'),
  ('brand','BAGLEY ARGENTINA S.A.'),
  ('brand','MATARAZZO'),
  ('brand','TUNKI POP'),
  ('brand','COMENSAL'),
  ('brand','GUSTOSO'),
  ('brand','RIAZOR'),
  ('brand','MENOYO'),
  ('brand','SAN HUBERTO'),
  ('brand','SIERRA DE LOS PADRES'),
  ('brand','BONAQUA'),
  ('brand','WE'),
  ('brand','CEPITA'),
  ('brand','HEINEKEN'),
  ('brand','SAINT FELICIEN'),
  ('brand','BARON B'),
  ('brand','CHANDON'),
  ('brand','NORTON'),
  ('brand','FUZE TEA'),
  ('brand','FANTA'),
  ('brand','SCHWEPPES'),
  ('brand','SPRITE'),
  ('brand','PRESTIGIO'),
  ('brand','SILVA'),
  ('brand','120 AÑOS'),
  ('brand','MINERVA'),
  ('brand','TUTTI'),
  ('brand','BAGGIO PRONTO'),
  ('brand','MOCORETA'),
  ('brand','BOLS'),
  ('brand','POWERADE'),
  ('brand','REAL'),
  ('brand','UVITA'),
  ('brand','DV CATENA'),
  ('brand','EL ABUELO'),
  ('brand','LATITUD 33'),
  ('brand','TRUMPETER'),
  ('brand','UXMAL'),
  ('brand','ARTESANO'),
  ('brand','SAFRA'),
  ('brand','MAGGI'),
  ('brand','BEDIAL'),
  ('brand','LOS VALLES'),
  ('brand','ALIMENSUR'),
  ('brand','CELUSAL'),
  ('brand','PALADINI'),
  ('brand','PATY'),
  ('brand','WHIM'),
  ('brand','TRES ARROYOS'),
  ('brand','BOULEVARES'),
  ('brand','CADBURY'),
  ('brand','DIVERSEY'),
  ('brand','MF'),
  ('brand','TARAGUI'),
  ('brand','UNION'),
  ('brand','CRUZ DE MALTA'),
  ('brand','DEL NOR'),
  ('brand','DORADA'),
  ('brand','NOBLEZA GAUCHA'),
  ('brand','ROSAMONTE'),
  ('brand','COLOSAL'),
  ('brand','DOS ESTRELLAS'),
  ('brand','GRANDOTE'),
  ('brand','DRF'),
  ('brand','HALLS'),
  ('brand','BELDENT'),
  ('brand','RHODESIA'),
  ('brand','ROYAL'),
  ('brand','CEREALITAS-GRANIX'),
  ('brand','NABISCO'),
  ('brand','ESTRELLA'),
  ('brand','ESENCIAL'),
  ('brand','EL BUDA'),
  ('brand','SANTA ISABEL'),
  ('brand','PATRICIA ALLEN'),
  ('brand','LUCCHETTI'),
  ('brand','SAN AGUSTIN'),
  ('brand','FAVORITA'),
  ('brand','LUCHETTI'),
  ('brand','ORLOC'),
  ('brand','BARBARA'),
  ('brand','SI - DIET'),
  ('brand','SILIGHT'),
  ('brand','DULKRE'),
  ('brand','HILERET'),
  ('brand','DEWEY'),
  ('brand','CASTELL'),
  ('brand','EL CRIOLLO'),
  ('brand','JAUBER'),
  ('brand','CARTE DOR'),
  ('brand','GREEN LIFE'),
  ('brand','ARCOR'),
  ('brand','NOEL'),
  ('brand','LA COLINA'),
  ('brand','POLETTI'),
  ('brand','LESANSI'),
  ('brand','OLINTO'),
  ('brand','AGROMAR'),
  ('brand','ARC'),
  ('brand','NESTLE'),
  ('brand','GRANCHEF'),
  ('brand','JANDIA'),
  ('brand','JANDAIA'),
  ('brand','SIERRA LEONA'),
  ('brand','SIETE LAGOS'),
  ('brand','MOLINOS CAÑUELAS'),
  ('brand','COPA DE ORO'),
  ('brand','COMAI'),
  ('brand','RECREO'),
  ('brand','CUYAIRES'),
  ('brand','CARALB'),
  ('brand','BLANCAFLOR'),
  ('brand','CASERITA'),
  ('brand','CHACABUCO'),
  ('brand','FLORENCIA'),
  ('brand','REIN HARINA'),
  ('brand','TASSARA'),
  ('brand','PRESTOPRONTA'),
  ('brand','DE LA HUERTA'),
  ('brand','SIETE DIAS'),
  ('brand','CAROYENSE'),
  ('brand','CICA'),
  ('brand','CORPER'),
  ('brand','SALSATI'),
  ('brand','PREFERIDO'),
  ('brand','MAMA COCINA'),
  ('brand','ROSA BLANCA'),
  ('brand','DOA ANA'),
  ('brand','DUL-C'),
  ('brand','EL CANUTO'),
  ('brand','LA MUECA'),
  ('brand','SANTA CAA'),
  ('brand','CHANGO'),
  ('brand','WILDE'),
  ('brand','LA TOSCANA'),
  ('brand','RENATA'),
  ('brand','LIRA'),
  ('brand','BILLIKEN'),
  ('brand','AQUARIUS'),
  ('brand','LEVITE'),
  ('brand','VILLA DEL SUR'),
  ('brand','VILLAVICENCIO'),
  ('brand','COCA'),
  ('brand','ABRA'),
  ('brand','SIEMBRAS Y CULTIVOS'),
  ('brand','DON SATUR'),
  ('brand','CHUMBALE'),
  ('brand','NUTRIMAX'),
  ('brand','MARBELLA'),
  ('brand','NOEL -'),
  ('brand','TERRABUSI'),
  ('brand','CLUB SOCIAL'),
  ('brand','PEPITOS'),
  ('brand','MENTITAS'),
  ('brand','MILKA'),
  ('brand','TRISHOT'),
  ('brand','TEREPIN'),
  ('brand','ARROZEN'),
  ('brand','MAC ZEN'),
  ('brand','OREO'),
  ('brand','SUGUS'),
  ('brand','NEREIDA'),
  ('brand','MELLINO'),
  ('brand','CASCABEL'),
  ('brand','PUNTA MAR'),
  ('brand','PUNTAMAR'),
  ('brand','YIN YANG'),
  ('brand','ESNALOA'),
  ('brand','ILOLAY'),
  ('brand','LATTE BAGGIO'),
  ('brand','SANDY'),
  ('brand','LA RUFINA'),
  ('brand','MAURIPAN'),
  ('brand','DULCIORA'),
  ('brand','SPALEN'),
  ('brand','EL RIBEÑO'),
  ('brand','CAÑUELAS'),
  ('brand','GRANJA DEL SOL'),
  ('brand','NUTRICIA BAGO'),
  ('brand','LIPO'),
  ('brand','MENTHOPLUS'),
  ('brand','MOGUL'),
  ('brand','BAGGIO LATTE'),
  ('brand','LHERITIER'),
  ('brand','LEE KUM LEE'),
  ('brand','HEI-MEN'),
  ('brand','FRUTOS DEL CIELO'),
  ('brand','VALLE DULCE'),
  ('brand','BARILLA'),
  ('brand','CANALE'),
  ('brand','MAGGIORE'),
  ('brand','DON VICENTE'),
  ('brand','PASTARROZ'),
  ('brand','SAGEMULLER'),
  ('brand','BAJITOS'),
  ('brand','TAXORENA'),
  ('brand','MAZOLA'),
  ('brand','PIAMONTESA'),
  ('brand','BAZOOKA'),
  ('brand','BUBBALOO'),
  ('brand','DOLCA'),
  ('brand','COFLER'),
  ('brand','CABSHA'),
  ('brand','CREMINO'),
  ('brand','STANI'),
  ('brand','SHOT'),
  ('brand','MANTECOL'),
  ('brand','ROCKLETS'),
  ('brand','HAMLET'),
  ('brand','RICREM'),
  ('brand','CALSA'),
  ('brand','SANCARLINA'),
  ('brand','BARRAZA'),
  ('brand','SUPERCREM'),
  ('brand','ARO'),
  ('brand','RICREM B.IMP'),
  ('brand','ARCOR S.A.I.C.-Div. Estirenos'),
  ('brand','IDEAL'),
  ('brand','LACTONA'),
  ('brand','ORIETA'),
  ('brand','ARGENFRUT'),
  ('brand','MISKY'),
  ('brand','NIHUIL'),
  ('brand','LL. DE ORO'),
  ('brand','KIN'),
  ('brand','3 ARROYOS'),
  ('brand','GRANIX'),
  ('brand','NANI'),
  ('brand','NEW CREAM'),
  ('brand','CARNEVALI'),
  ('brand','ESTANCIA EL PLACER'),
  ('brand','PAMPA ZANATTA'),
  ('brand','LA SERENISIMA'),
  ('brand','FRIG. ENTRE TODOS'),
  ('brand','ODERICH'),
  ('brand','RONCHI'),
  ('brand','TARRAGONA'),
  ('brand','INCA'),
  ('brand','GENTLEMAN'),
  ('brand','CAÑUELAS/COCINERO'),
  ('brand','SUPERKAO'),
  ('brand','ZUCOA'),
  ('brand','DHUNCRAK'),
  ('brand','PUREZA'),
  ('brand','POZO'),
  ('brand','NEVARES'),
  ('brand','EXCLUSIVO'),
  ('brand','DELICIAS DE LA NONNA'),
  ('brand','VITINA'),
  ('brand','LA HOJA'),
  ('brand','EQUIAL SWEET'),
  ('brand','BOSTON'),
  ('brand','URRUTIA'),
  ('brand','HEREDIA'),
  ('brand','CHAMANA'),
  ('brand','CACHAMAI'),
  ('brand','MENDIA'),
  ('brand','SUMASA'),
  ('brand','EL SOL DE BELLA VISTA'),
  ('brand','DIS-TAP'),
  ('brand','TAPALQUE'),
  ('brand','FRIGOR NESTLE'),
  ('brand','LA MORENITA'),
  ('brand','SINDY'),
  ('brand','NANDO'),
  ('brand','AGIBO'),
  ('brand','BONVENTO'),
  ('brand','CASALIVA'),
  ('brand','ALSAMAR'),
  ('brand','DOÑA ROSA'),
  ('brand','HUACO'),
  ('brand','PETIRIBI'),
  ('brand','LECHE EN POLVO'),
  ('brand','BAGGIO LATTE KIDS'),
  ('brand','LA BIANCA'),
  ('brand','JET FOOD'),
  ('brand','LA COMARCA'),
  ('brand','PARMALAT'),
  ('brand','TREGAR'),
  ('brand','LA BASTILLA'),
  ('brand','WAPI'),
  ('brand','MILKAUT'),
  ('brand','CREMIGAL'),
  ('brand','SHEHUEN'),
  ('brand','VERONICA'),
  ('brand','MOZZARI'),
  ('brand','TONUTTI'),
  ('brand','LA MANSA'),
  ('brand','SANTA ROSA'),
  ('brand','SAN ISIDRO'),
  ('brand','SAN IGNACIO'),
  ('brand','LA QUESERA'),
  ('brand','SPRETZ'),
  ('brand','TRELAU'),
  ('brand','DANICA'),
  ('brand','MANSA'),
  ('brand','LA OCTAVA'),
  ('brand','CAMPO AUSTRAL'),
  ('brand','SELLO DE ORO'),
  ('brand','SERRANITO'),
  ('brand','HORECA'),
  ('brand','PIERES'),
  ('brand','LABRATTO'),
  ('brand','ITALIANA'),
  ('brand','GONZALEZ'),
  ('brand','LABROIER'),
  ('brand','DON JORGE'),
  ('brand','SELLO DE PLATA'),
  ('brand','MONTESANO'),
  ('brand','CAGNOLI'),
  ('brand','TORGELONE'),
  ('brand','ERIN'),
  ('brand','HEINLEIN'),
  ('brand','RAPIMIX'),
  ('brand','RAPIPAP'),
  ('brand','SUPERFARM'),
  ('brand','VEGETALEX'),
  ('brand','G. DE LA PAMPA'),
  ('brand','YANCANELLO'),
  ('brand','INDALO'),
  ('brand','O. DEL NORTE'),
  ('brand','ZUELO'),
  ('brand','ARISCO'),
  ('brand','LAS TOSCANA'),
  ('brand','SAN GIORGIO'),
  ('brand','ARRIGHI'),
  ('brand','EL CELTA'),
  ('brand','TAU DELTA'),
  ('brand','HEINZ'),
  ('brand','PRUGNA'),
  ('brand','GENSER'),
  ('brand','EGEO'),
  ('brand','OTAMENDI'),
  ('brand','MAILLE'),
  ('brand','TWININGS'),
  ('brand','JORGITO'),
  ('brand','DOÑA AMPARO'),
  ('brand','FENIX'),
  ('brand','SUSANA VIDA'),
  ('brand','QUENTO'),
  ('brand','MINGO'),
  ('brand','GOOD SHOW'),
  ('brand','MC JOE'),
  ('brand','OPERA'),
  ('brand','RECITAL'),
  ('brand','CABRALES'),
  ('brand','LA TRANQUERA'),
  ('brand','LA VIRGINIA'),
  ('brand','GREEN HILLS'),
  ('brand','PUROCOL'),
  ('brand','QUILMES'),
  ('brand','ALMA MORA'),
  ('brand','TRAPICHE'),
  ('brand','NAVARRO CORREAS'),
  ('brand','ALAMOS'),
  ('brand','POMMERY'),
  ('brand','SUTER'),
  ('brand','REINO DE CASTILLA'),
  ('brand','LA VICTORIA'),
  ('brand','9 DE ORO'),
  ('brand','TRIO'),
  ('brand','TODDY'),
  ('brand','VALENTE'),
  ('brand','BAGGIO FRESH'),
  ('brand','BAGGIO LIGHT'),
  ('brand','BAGGIO VIDA'),
  ('brand','FLIP'),
  ('brand','SER'),
  ('brand','BIZNIKKE'),
  ('brand','GUALCO'),
  ('brand','ARTICO'),
  ('brand','PRINCETON'),
  ('brand','BAY BISCUIT'),
  ('brand','BEETHOVEN'),
  ('brand','TALACASTO'),
  ('brand','CAVIC'),
  ('brand','LA VID'),
  ('brand','LA LIEBRE'),
  ('brand','PHILADELPHIA'),
  ('brand','ARIZU'),
  ('brand','GANADOR'),
  ('brand','GLACIAR'),
  ('brand','CINDOR'),
  ('brand','FLYNN PAFF'),
  ('brand','VAUQUITA'),
  ('brand','PAR NOR'),
  ('brand','NOAL'),
  ('brand','MONTE CASTRO'),
  ('brand','DOBLE A'),
  ('brand','LOS 4 HERMANOS'),
  ('brand','LOMSICAR'),
  ('brand','SILMORI'),
  ('brand','DON JULIAN'),
  ('brand','TONADITA'),
  ('brand','AMANECER'),
  ('brand','FRIG. LOS CORDOBESES'),
  ('brand','LAS TRES NIÑAS'),
  ('brand','SANCOR'),
  ('brand','INTI-ZEN'),
  ('brand','TITA'),
  ('brand','CASANCREM'),
  ('brand','LA RECOLETA'),
  ('brand','SANTA MARIA'),
  ('brand','NATUZEN'),
  ('brand','MARBE'),
  ('brand','DONOSTI'),
  ('brand','CEREAL MIX'),
  ('brand','SILVIA'),
  ('brand','VACREM'),
  ('brand','LEMBOS'),
  ('brand','LA HERMINIA'),
  ('brand','DULCEMAR'),
  ('brand','FAVALORO'),
  ('brand','EL MARQUES'),
  ('brand','FINCA DE SANTIAGO'),
  ('brand','MACRITAS'),
  ('brand','NEW AGE'),
  ('brand','NONNA PIA'),
  ('brand','PAISANITA'),
  ('brand','BOCATTI'),
  ('brand','FRIOLIM'),
  ('brand','LEIG LAC'),
  ('brand','LA MODESTA'),
  ('brand','PUNTA DEL AGUA'),
  ('brand','DULCOR'),
  ('brand','LA JOYA'),
  ('brand','LOMAS'),
  ('brand','MOLINOS DEL BOSQUE'),
  ('brand','CARICIAS'),
  ('brand','DISMAY'),
  ('brand','GUAYMALLEN'),
  ('brand','NEOSOL'),
  ('brand','MARISOL'),
  ('brand','PIBITOS'),
  ('brand','EDEMY'),
  ('brand','DULCYPAS'),
  ('brand','FATAY'),
  ('brand','TURIMAR'),
  ('brand','EDDING'),
  ('brand','SAKURA'),
  ('brand','SYLVAPEN'),
  ('brand','CUPIDO'),
  ('brand','ANMAT'),
  ('brand','SPAT'),
  ('brand','MELINCUE'),
  ('brand','LEVINA'),
  ('brand','CLOVELLY'),
  ('brand','ALZAMAR'),
  ('brand','MARCELITO'),
  ('brand','LEGITIMO'),
  ('brand','NIETO SENETINER'),
  ('brand','DUJAM'),
  ('brand','MARISCAL'),
  ('brand','S Y S'),
  ('brand','FOX'),
  ('brand','PEHUAMAR'),
  ('brand','MARDI'),
  ('brand','ENRICO BARONESE'),
  ('brand','NUTRIFOOD'),
  ('brand','HAVANNA'),
  ('brand','LA POMPEYA'),
  ('brand','CRSF'),
  ('brand','CRYSF'),
  ('brand','CORUM'),
  ('brand','BARISTA'),
  ('brand','BENIDORM'),
  ('brand','MYK'),
  ('brand','BC'),
  ('brand','HALCONERO'),
  ('brand','LA MUÑECA'),
  ('brand','EVEREST'),
  ('brand','L. ROJA'),
  ('brand','POP XXI'),
  ('brand','CAUTIVA'),
  ('brand','BREVISS'),
  ('brand','JUVIN'),
  ('brand','LIMONESSI'),
  ('brand','CITRIC'),
  ('brand','MR CHOCO'),
  ('brand','SANTA ELENE'),
  ('brand','LA BABILONIA'),
  ('brand','GEORGALOS'),
  ('brand','DON MARCOS'),
  ('brand','LA MOCITA'),
  ('brand','NORY'),
  ('brand','ZUPAY'),
  ('brand','CIMES'),
  ('brand','CUSENIER'),
  ('brand','BON MASE'),
  ('brand','AMANDA'),
  ('brand','TIA MARUCA'),
  ('brand','MOROCHITAS'),
  ('brand','PUNTA CHICA'),
  ('brand','MANFREY'),
  ('brand','PALMESANO'),
  ('brand','ALQUILER'),
  ('brand','REPOSICION'),
  ('brand','GRIDO'),
  ('brand','HJ'),
  ('brand','DEL VALLE'),
  ('brand','ALSINA DEPOT'),
  ('brand','DEL SOL'),
  ('brand','DR CORMILLOT'),
  ('brand','LA BIZANTINA'),
  ('brand','EDRA'),
  ('brand','PITUSAS'),
  ('brand','MONTEALTO'),
  ('brand','BAHIA'),
  ('brand','URQUIZA'),
  ('brand','VIMAR'),
  ('brand','CV'),
  ('brand','LA SALTEÑA'),
  ('brand','BIMBO'),
  ('brand','LA ABADIA'),
  ('brand','TAHITI'),
  ('brand','BITARWAN'),
  ('brand','FAVINCO'),
  ('brand','LA BOLSA DE CAFE'),
  ('brand','FLOW'),
  ('brand','CEREANOLA'),
  ('brand','PERCAL'),
  ('brand','LO PREITE'),
  ('brand','LACTAL'),
  ('brand','IL PANETTO'),
  ('brand','FURA'),
  ('brand','CAMPOS ANDINOS'),
  ('brand','SEPTIEMBRE'),
  ('brand','GOLACTEOS'),
  ('brand','GOMES DA COSTA'),
  ('brand','FRESCO PEZ'),
  ('brand','ALAMENIA'),
  ('brand','FLEIBOR'),
  ('brand','OKLAHOMA'),
  ('brand','JORGELIN'),
  ('brand','PASTAS LUCIO'),
  ('brand','HARINISIMA'),
  ('brand','VIENTO NORTE'),
  ('brand','CASALTA'),
  ('brand','MAPSA'),
  ('brand','CASTELLO PONTE'),
  ('brand','MARILY'),
  ('brand','CONCIENCIA'),
  ('brand','FACHITAS'),
  ('brand','DELUXE'),
  ('brand','FULLSTRIP'),
  ('brand','FANTOCHE'),
  ('brand','JUSTO'),
  ('brand','CANETTINE'),
  ('brand','NOVECENTO'),
  ('brand','HEREFORD'),
  ('brand','POSTALES DEL FIN DEL MUNDO'),
  ('brand','BENJAMIN NIETO SENETINER'),
  ('brand','ABSOLUT'),
  ('brand','PROMESA'),
  ('brand','STELLA ARTOIS'),
  ('brand','TIBURON'),
  ('brand','OLIVARES DEL SOL'),
  ('brand','FURA DIRECTO CABA'),
  ('brand','FURA DIRECTO PROVINCIA'),
  ('brand','RECETAS DE LA ABUELA'),
  ('brand','BONOMI'),
  ('brand','POLINORTE'),
  ('brand','YOVINESA'),
  ('brand','Den'),
  ('brand','ALCO'),
  ('brand','RESERO'),
  ('brand','CARACAS'),
  ('brand','ELEGANTE'),
  ('brand','LODISER'),
  ('brand','POSTREFINO'),
  ('brand','ROMANCE'),
  ('brand','MACUCA'),
  ('brand','PUGLISI'),
  ('brand','ATMA'),
  ('brand','OKEBON'),
  ('brand','CULLIGAN'),
  ('brand','PANIFICADORA SEL SUR'),
  ('brand','IMAX'),
  ('brand','TERRAMARE'),
  ('brand','PRESIDENT'),
  ('brand','FOR GOOD'),
  ('brand','GREEN CHOICE'),
  ('brand','BOCHIN'),
  ('brand','PIPAS'),
  ('brand','CROTTA'),
  ('brand','SEI TU'),
  ('brand','CARILO'),
  ('brand','LA MODERNA'),
  ('brand','LULEMUU'),
  ('brand','NUCETE'),
  ('brand','LANUS'),
  ('brand','la casona'),
  ('brand','LA RESIDENCIA'),
  ('brand','ZEBRA'),
  ('brand','SODECAR'),
  ('brand','STIKO'),
  ('brand','TOFI'),
  ('brand','PHILCO'),
  ('brand','POETT'),
  ('brand','CALLIA'),
  ('brand','SIMBALL'),
  ('brand','ONIX'),
  ('brand','TALLE 2'),
  ('brand','TALLE 3'),
  ('brand','TALLE 5'),
  ('brand','TALLE 6'),
  ('brand','TALLE 7'),
  ('brand','TALLE 8'),
  ('brand','TALLE 4'),
  ('brand','TALLE M/42'),
  ('brand','TALLE 46'),
  ('brand','TALLE 42'),
  ('brand','TALLE 48'),
  ('brand','TALLE 37'),
  ('brand','TALLE 38'),
  ('brand','TALLE 43'),
  ('brand','TALLE 41'),
  ('brand','TALLE 39'),
  ('brand','TALLE 40'),
  ('brand','TALLE 45'),
  ('brand','CARAMELIZADO'),
  ('brand','FARGO'),
  ('brand','CAROGRAN'),
  ('brand','KUWI'),
  ('brand','GENIUS'),
  ('brand','PAGODA'),
  ('brand','NESPRESSO'),
  ('brand','monterrey'),
  ('brand','CRISTO DE LOS CERROS'),
  ('brand','EL PUELO'),
  ('brand','JULICROCK'),
  ('brand','BLEM'),
  ('brand','AYUDIN'),
  ('brand','CIF'),
  ('brand','OBLITA'),
  ('brand','LA TIENDA SIN GLUTEN'),
  ('brand','PRIMER PREMIO'),
  ('brand','UNOX'),
  ('brand','3M'),
  ('brand','CELEBES COCONUT'),
  ('brand','COCO DO VALE'),
  ('brand','SOCOCO'),
  ('brand','ALOA'),
  ('brand','COXI'),
  ('brand','EZCO'),
  ('brand','AVON'),
  ('brand','POTOSI'),
  ('brand','DIMAX'),
  ('brand','GRIDO DIRECTO'),
  ('brand','SOYARROZ'),
  ('brand','SALVITA'),
  ('brand','FINESCHI'),
  ('brand','NUTRISUR'),
  ('brand','PAMPA'),
  ('brand','VACACAY'),
  ('brand','CAROL'),
  ('brand','LUJUS'),
  ('brand','MONTENEVI'),
  ('brand','POMMIER'),
  ('brand','COTO'),
  ('brand','ANAMARKET'),
  ('brand','STOCK 8'),
  ('brand','PURISIMA'),
  ('brand','OROWEAT'),
  ('brand','POLVORITA'),
  ('brand','ACERMEL'),
  ('brand','NORTH TIGER'),
  ('brand','COQUIM'),
  ('brand','PEABODY'),
  ('brand','RICHARD'),
  ('brand','HUSARES'),
  ('brand','FABER CASTELL'),
  ('brand','LA PARMESANA'),
  ('brand','CAPULLITOS EN FLOR'),
  ('brand','POYIN'),
  ('brand','TALLE 1'),
  ('brand','GRANJA MARTIN'),
  ('brand','TALLE 35'),
  ('brand','TALLE 36'),
  ('brand','TALLE 44'),
  ('brand','NOLY'),
  ('brand','Kellness'),
  ('brand','ASAMBLEA'),
  ('brand','INFAN TEC'),
  ('brand','TALLE 9'),
  ('brand','TALLE 10'),
  ('brand','EL TIMON'),
  ('brand','EGRAN'),
  ('brand','CARREFOUR'),
  ('brand','PAUNA'),
  ('brand','BRAUN'),
  ('brand','SANTA CLARA'),
  ('brand','DIA'),
  ('brand','LIBUS'),
  ('brand','SOYCHU'),
  ('brand','RCA'),
  ('brand','FORNES'),
  ('brand','SAN JUANITA'),
  ('brand','ALPINO'),
  ('brand','TERMOLAR'),
  ('brand','EL CIERVO'),
  ('brand','MOLINOS ALA'),
  ('brand','MOULINEX'),
  ('brand','FINCA CRIOLLA'),
  ('brand','SOITUE'),
  ('brand','TALLE XL'),
  ('brand','TALLE L'),
  ('brand','MAKRO'),
  ('brand','LINCOLN'),
  ('brand','SNUKS'),
  ('brand','MACROBIATICAS'),
  ('brand','AYF'),
  ('brand','DORITOS'),
  ('brand','PANFROST'),
  ('brand','SYSTEL'),
  ('brand','TRINIDAD'),
  ('brand','ENERGIZER'),
  ('brand','MANJARES DEL MAR'),
  ('brand','GOLD MUNDO'),
  ('brand','CASA ROJO'),
  ('brand','TALLES COMUNES'),
  ('brand','TALLES ESPECIALES'),
  ('brand','PIÑATA'),
  ('brand','CAMPERO'),
  ('brand','JUABER'),
  ('brand','NON PAREIL'),
  ('brand','NUEVO HAEDO'),
  ('brand','BLEACH'),
  ('brand','DIONE'),
  ('brand','BARI'),
  ('brand','SULTANITA'),
  ('brand','ALTEZA'),
  ('brand','PROIN'),
  ('brand','LEUDEX'),
  ('brand','ANTHONY'),
  ('brand','ALICANTE'),
  ('brand','PEREZ'),
  ('brand','BRANCA'),
  ('brand','CORONA'),
  ('brand','ARRIVATA'),
  ('brand','SAN CIPRIANO'),
  ('brand','ESPUÑA'),
  ('brand','LEMVA'),
  ('brand','LA DELFINA'),
  ('brand','BARILOCHE'),
  ('brand','MARVI'),
  ('brand','JUMBO'),
  ('brand','DOÑA MARIA'),
  ('brand','PROLYDEN'),
  ('brand','SATCHMO'),
  ('brand','KAPAC'),
  ('brand','PACHIN'),
  ('brand','ALIMAX'),
  ('brand','CANUN'),
  ('brand','RICABE'),
  ('brand','JUMALA'),
  ('brand','NIKITOS'),
  ('brand','SILVINA'),
  ('brand','LAS HERAS'),
  ('brand','MATE GRAS'),
  ('brand','ALELUYA'),
  ('brand','DELOSAN'),
  ('brand','EL PUENTE'),
  ('brand','LA PERLA'),
  ('brand','FATY'),
  ('brand','GLADE'),
  ('brand','VILLARE'),
  ('brand','LYSOFORM'),
  ('brand','HONEYWELL'),
  ('brand','DEL TURISTA'),
  ('brand','CORDOBESA'),
  ('brand','FAINALIND'),
  ('brand','TALLE XXL'),
  ('brand','LUZ AZUL'),
  ('brand','CRONWELL'),
  ('brand','VENEZIANA'),
  ('brand','YOLANKA'),
  ('brand','COTAR'),
  ('brand','COTAPA'),
  ('brand','GIO'),
  ('brand','LEIVA'),
  ('brand','LA VACA CUADRADA'),
  ('brand','DON ROQUE'),
  ('brand','AZUCEL'),
  ('brand','CONDESA'),
  ('brand','EL CALDEN'),
  ('brand','LECHERISIMA'),
  ('brand','MAGER DAGEN'),
  ('brand','NUTREGAL'),
  ('brand','MORA'),
  ('brand','LA EGIPCIANA'),
  ('brand','CREMACHEL'),
  ('brand','SCHWARZBIER'),
  ('brand','LA DIVISA'),
  ('brand','WAMIS'),
  ('brand','PROGEL'),
  ('brand','SUPER BLEACH'),
  ('brand','RINSEC 2'),
  ('brand','DETERLIQ PLUS 2'),
  ('brand','DEOSOL'),
  ('brand','ECODISH'),
  ('brand','BACHAND'),
  ('brand','LA JUVENIL'),
  ('brand','JUMBALAY'),
  ('brand','FINCA AREZZO'),
  ('brand','NEVADA'),
  ('brand','CHIQUI LIGHT'),
  ('brand','LA VENERADA'),
  ('brand','WACAMAY'),
  ('brand','VAQUERO'),
  ('brand','ANGELITA'),
  ('brand','COTNYL'),
  ('brand','ALUMAX'),
  ('brand','WORK'),
  ('brand','BARMAN'),
  ('brand','EXPOLAC'),
  ('brand','SACAAN'),
  ('brand','BKS PALETAS'),
  ('brand','TRIHEL'),
  ('brand','COLEMAN'),
  ('brand','FINCA BALCARCE'),
  ('brand','UNION GANADERA'),
  ('brand','LA LACTEO'),
  ('brand','LONG DOG'),
  ('brand','ECOFORMAS'),
  ('brand','BEMIS'),
  ('brand','ISOPOR'),
  ('brand','PLASTICOS BOULEVARES'),
  ('brand','ORALI'),
  ('brand','TREMBLAY'),
  ('brand','ARTI'),
  ('brand','LA MOROCHA'),
  ('brand','OLITAS'),
  ('brand','CACHAFAZ'),
  ('brand','MELTAIM'),
  ('brand','YAMOA'),
  ('brand','MORGADE'),
  ('brand','PLENY'),
  ('brand','OKEY'),
  ('brand','OLIOVITA'),
  ('brand','COINCO'),
  ('brand','LECHELITA'),
  ('brand','MONALISA'),
  ('brand','PAGOS DEL SUR'),
  ('brand','DELICEL'),
  ('brand','FUMEIGA'),
  ('brand','CABAÑA ARGENTINA'),
  ('brand','CERRO AZUL'),
  ('brand','MAURI'),
  ('brand','MEDIA TARDE'),
  ('brand','FANTASIA'),
  ('brand','GAONA'),
  ('brand','RATIONAL'),
  ('brand','MI MARCA')
on conflict do nothing;

commit;

