-- MVP RRHH > Uniformes y EPP. REQUIERE AUTORIZACION EXPLICITA ANTES DE APLICAR.
-- Proyecto exclusivo: mixyhfdlzjarvszinytk.

create table equipo.epp_catalogo (
  id uuid primary key default gen_random_uuid(),
  codigo text not null unique,
  nombre text not null,
  categoria text not null check (categoria in ('uniforme','epp','calzado','credencial','otro')),
  descripcion text,
  marca_modelo text,
  vida_util_meses integer check (vida_util_meses is null or vida_util_meses > 0),
  requiere_devolucion boolean not null default false,
  reposicion_periodica boolean not null default false,
  imagen_path text,
  activo boolean not null default true,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table equipo.epp_catalogo_talles (
  id bigint generated by default as identity primary key,
  producto_id uuid not null references equipo.epp_catalogo(id) on delete cascade,
  talle text not null,
  activo boolean not null default true,
  unique(producto_id,talle)
);

create sequence equipo.epp_envio_codigo_seq;
create table equipo.epp_envios (
  id uuid primary key default gen_random_uuid(),
  codigo text not null unique default ('FK-EPP-' || extract(year from current_date)::int || '-' || lpad(nextval('equipo.epp_envio_codigo_seq')::text,5,'0')),
  sede_id integer not null references bitacora.sedes(id),
  estado text not null default 'borrador' check (estado in ('borrador','preparado','despachado','recibido_sede','distribucion_parcial','completado','cancelado')),
  fecha_preparacion date,
  fecha_despacho timestamptz,
  responsable_envio_id uuid references equipo.personas(id),
  observaciones text,
  qr_token_hash text unique,
  qr_habilitado boolean not null default false,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table equipo.epp_envio_items (
  id uuid primary key default gen_random_uuid(),
  envio_id uuid not null references equipo.epp_envios(id) on delete cascade,
  producto_id uuid not null references equipo.epp_catalogo(id),
  persona_id uuid references equipo.personas(id),
  talle text,
  cantidad integer not null default 1 check (cantidad > 0),
  estado text not null default 'pendiente' check (estado in ('pendiente','recibido_sede','entregado','confirmado','observado','no_recibido','devuelto','repuesto','cancelado')),
  observaciones text,
  created_at timestamptz not null default now()
);

create table equipo.epp_envio_bultos (
  id uuid primary key default gen_random_uuid(),
  envio_id uuid not null references equipo.epp_envios(id) on delete cascade,
  numero integer not null check (numero > 0),
  codigo text not null unique,
  descripcion text,
  estado text not null default 'preparado' check (estado in ('preparado','despachado','recibido','observado','faltante','cancelado')),
  qr_token_hash text not null unique,
  qr_habilitado boolean not null default true,
  recibido_at timestamptz,
  receptor_persona_id uuid references equipo.personas(id),
  observaciones_recepcion text,
  created_at timestamptz not null default now(),
  unique(envio_id,numero)
);

create table equipo.epp_bulto_items (
  bulto_id uuid not null references equipo.epp_envio_bultos(id) on delete cascade,
  envio_item_id uuid not null references equipo.epp_envio_items(id) on delete cascade,
  cantidad integer not null check (cantidad > 0),
  primary key(bulto_id,envio_item_id)
);

create table equipo.epp_recepciones_sede (
  id uuid primary key default gen_random_uuid(),
  envio_id uuid not null references equipo.epp_envios(id),
  bulto_id uuid references equipo.epp_envio_bultos(id),
  receptor_persona_id uuid not null references equipo.personas(id),
  cantidad_bultos integer not null default 1 check (cantidad_bultos > 0),
  resultado text not null check (resultado in ('conforme','con_observaciones','rechazado')),
  observaciones text,
  recibido_at timestamptz not null default now(),
  registrado_by uuid references auth.users(id),
  unique(envio_id,receptor_persona_id,recibido_at)
);

create table equipo.epp_entregas_personal (
  id uuid primary key default gen_random_uuid(),
  envio_item_id uuid not null references equipo.epp_envio_items(id),
  persona_id uuid not null references equipo.personas(id),
  producto_id uuid not null references equipo.epp_catalogo(id),
  sede_id integer not null references bitacora.sedes(id),
  talle text,
  cantidad integer not null default 1 check (cantidad > 0),
  estado text not null default 'entregado' check (estado in ('entregado','confirmado','observado','no_recibido','devuelto','repuesto')),
  conformidad text check (conformidad is null or conformidad in ('conforme','con_observaciones','no_recibido')),
  entregado_at timestamptz not null default now(),
  confirmado_at timestamptz,
  entregado_por uuid references equipo.personas(id),
  observaciones text,
  unique(envio_item_id,persona_id)
);

create table equipo.epp_validaciones (
  id uuid primary key default gen_random_uuid(),
  entrega_id uuid not null references equipo.epp_entregas_personal(id),
  persona_id uuid not null references equipo.personas(id),
  metodo text not null check (metodo in ('email_otp','usuario_fly','administrativa')),
  dni_ultimos_4 text check (dni_ultimos_4 is null or dni_ultimos_4 ~ '^[0-9]{4}$'),
  email_mascarado text,
  sesion_hash text,
  ip_hash text,
  resultado text not null check (resultado in ('confirmado','rechazado','expirado')),
  validado_at timestamptz not null default now()
);

create table equipo.epp_incidencias (
  id uuid primary key default gen_random_uuid(),
  envio_item_id uuid references equipo.epp_envio_items(id),
  entrega_id uuid references equipo.epp_entregas_personal(id),
  persona_id uuid references equipo.personas(id),
  tipo text not null check (tipo in ('talle_incorrecto','producto_danado','cantidad_incorrecta','faltante','perdida','rotura','reposicion','otro')),
  descripcion text,
  foto_path text,
  estado text not null default 'abierta' check (estado in ('abierta','en_gestion','resuelta')),
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  resolved_at timestamptz,
  check (envio_item_id is not null or entrega_id is not null)
);

create table equipo.epp_eventos (
  id bigint generated by default as identity primary key,
  envio_id uuid references equipo.epp_envios(id),
  entrega_id uuid references equipo.epp_entregas_personal(id),
  tipo text not null,
  actor_id uuid references auth.users(id),
  detalle text,
  datos jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  check (envio_id is not null or entrega_id is not null)
);

create index epp_envios_sede_estado_idx on equipo.epp_envios(sede_id,estado);
create index epp_items_envio_persona_idx on equipo.epp_envio_items(envio_id,persona_id);
create index epp_bultos_envio_estado_idx on equipo.epp_envio_bultos(envio_id,estado);
create index epp_entregas_persona_fecha_idx on equipo.epp_entregas_personal(persona_id,entregado_at desc);
create index epp_eventos_envio_fecha_idx on equipo.epp_eventos(envio_id,created_at desc);

alter table equipo.epp_catalogo enable row level security;
alter table equipo.epp_catalogo_talles enable row level security;
alter table equipo.epp_envios enable row level security;
alter table equipo.epp_envio_items enable row level security;
alter table equipo.epp_envio_bultos enable row level security;
alter table equipo.epp_bulto_items enable row level security;
alter table equipo.epp_recepciones_sede enable row level security;
alter table equipo.epp_entregas_personal enable row level security;
alter table equipo.epp_validaciones enable row level security;
alter table equipo.epp_incidencias enable row level security;
alter table equipo.epp_eventos enable row level security;

grant usage on schema equipo to authenticated;
grant select,insert,update on equipo.epp_catalogo,equipo.epp_catalogo_talles,equipo.epp_envios,equipo.epp_envio_items,equipo.epp_envio_bultos,equipo.epp_bulto_items,equipo.epp_recepciones_sede,equipo.epp_entregas_personal,equipo.epp_incidencias to authenticated;
grant select on equipo.epp_validaciones,equipo.epp_eventos to authenticated;
grant insert on equipo.epp_eventos to authenticated;
grant usage,select on sequence equipo.epp_envio_codigo_seq,equipo.epp_catalogo_talles_id_seq,equipo.epp_eventos_id_seq to authenticated;

create policy epp_catalogo_read on equipo.epp_catalogo for select to authenticated using (true);
create policy epp_talles_read on equipo.epp_catalogo_talles for select to authenticated using (true);
create policy epp_catalogo_admin_write on equipo.epp_catalogo for all to authenticated
using (exists(select 1 from bitacora.perfiles p where p.id=(select auth.uid()) and p.activo and p.rol in ('admin','editor')))
with check (exists(select 1 from bitacora.perfiles p where p.id=(select auth.uid()) and p.activo and p.rol in ('admin','editor')));
create policy epp_talles_admin_write on equipo.epp_catalogo_talles for all to authenticated
using (exists(select 1 from bitacora.perfiles p where p.id=(select auth.uid()) and p.activo and p.rol in ('admin','editor')))
with check (exists(select 1 from bitacora.perfiles p where p.id=(select auth.uid()) and p.activo and p.rol in ('admin','editor')));

create policy epp_envios_scoped_read on equipo.epp_envios for select to authenticated using (
  exists(select 1 from bitacora.perfiles p where p.id=(select auth.uid()) and p.activo and (p.rol in ('admin','editor','consultor') or sede_id=any(coalesce(p.sede_ids,'{}'::integer[])) or (p.rol='grupo' and exists(select 1 from bitacora.sedes s where s.id=sede_id and s.grupo_id=p.grupo_id))))
);
create policy epp_envios_scoped_write on equipo.epp_envios for all to authenticated
using (exists(select 1 from bitacora.perfiles p where p.id=(select auth.uid()) and p.activo and (p.rol in ('admin','editor') or sede_id=any(coalesce(p.sede_ids,'{}'::integer[])) or (p.rol='grupo' and exists(select 1 from bitacora.sedes s where s.id=sede_id and s.grupo_id=p.grupo_id)))))
with check (exists(select 1 from bitacora.perfiles p where p.id=(select auth.uid()) and p.activo and (p.rol in ('admin','editor') or sede_id=any(coalesce(p.sede_ids,'{}'::integer[])) or (p.rol='grupo' and exists(select 1 from bitacora.sedes s where s.id=sede_id and s.grupo_id=p.grupo_id)))));

create policy epp_items_scoped on equipo.epp_envio_items for all to authenticated
using (exists(select 1 from equipo.epp_envios e where e.id=envio_id))
with check (exists(select 1 from equipo.epp_envios e where e.id=envio_id));
create policy epp_bultos_scoped on equipo.epp_envio_bultos for all to authenticated
using (exists(select 1 from equipo.epp_envios e where e.id=envio_id))
with check (exists(select 1 from equipo.epp_envios e where e.id=envio_id));
create policy epp_bulto_items_scoped on equipo.epp_bulto_items for all to authenticated
using (exists(select 1 from equipo.epp_envio_bultos b join equipo.epp_envios e on e.id=b.envio_id where b.id=bulto_id))
with check (exists(select 1 from equipo.epp_envio_bultos b join equipo.epp_envios e on e.id=b.envio_id where b.id=bulto_id));
create policy epp_recepciones_scoped on equipo.epp_recepciones_sede for all to authenticated
using (exists(select 1 from equipo.epp_envios e where e.id=envio_id))
with check (exists(select 1 from equipo.epp_envios e where e.id=envio_id));
create policy epp_entregas_scoped on equipo.epp_entregas_personal for all to authenticated
using (exists(select 1 from equipo.epp_envios e join equipo.epp_envio_items i on i.envio_id=e.id where i.id=envio_item_id))
with check (exists(select 1 from equipo.epp_envios e join equipo.epp_envio_items i on i.envio_id=e.id where i.id=envio_item_id));
create policy epp_incidencias_scoped on equipo.epp_incidencias for all to authenticated
using (exists(select 1 from bitacora.perfiles p join equipo.personas persona on persona.id=epp_incidencias.persona_id where p.id=(select auth.uid()) and p.activo and (p.rol in ('admin','editor') or persona.sede_ids && coalesce(p.sede_ids,'{}'::integer[]))))
with check (exists(select 1 from bitacora.perfiles p join equipo.personas persona on persona.id=epp_incidencias.persona_id where p.id=(select auth.uid()) and p.activo and (p.rol in ('admin','editor') or persona.sede_ids && coalesce(p.sede_ids,'{}'::integer[]))));
create policy epp_validaciones_admin_read on equipo.epp_validaciones for select to authenticated using (exists(select 1 from bitacora.perfiles p where p.id=(select auth.uid()) and p.activo and p.rol in ('admin','editor')));
create policy epp_eventos_scoped_read on equipo.epp_eventos for select to authenticated using (envio_id is null or exists(select 1 from equipo.epp_envios e where e.id=envio_id));
create policy epp_eventos_scoped_insert on equipo.epp_eventos for insert to authenticated with check (actor_id=(select auth.uid()) and (envio_id is null or exists(select 1 from equipo.epp_envios e where e.id=envio_id)));

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values
('epp-catalogo','epp-catalogo',false,5242880,array['image/jpeg','image/png','image/webp']),
('epp-incidencias','epp-incidencias',false,10485760,array['image/jpeg','image/png','image/webp','application/pdf'])
on conflict(id) do update set public=excluded.public,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;

create policy epp_catalogo_storage_read on storage.objects for select to authenticated using (bucket_id='epp-catalogo');
create policy epp_catalogo_storage_write on storage.objects for insert to authenticated with check (bucket_id='epp-catalogo' and exists(select 1 from bitacora.perfiles p where p.id=(select auth.uid()) and p.activo and p.rol in ('admin','editor')));
create policy epp_incidencias_storage_read on storage.objects for select to authenticated using (bucket_id='epp-incidencias' and exists(select 1 from bitacora.perfiles p where p.id=(select auth.uid()) and p.activo and p.rol in ('admin','editor','grupo','encargado')));
create policy epp_incidencias_storage_write on storage.objects for insert to authenticated with check (bucket_id='epp-incidencias' and exists(select 1 from bitacora.perfiles p where p.id=(select auth.uid()) and p.activo and p.rol in ('admin','editor','grupo','encargado')));

comment on table equipo.epp_eventos is 'Trazabilidad append-only de Uniformes y EPP; no se otorgan UPDATE ni DELETE.';
